import { existsSync, readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'
import ts from 'typescript'

import { runtimeComponentNames } from './generated/runtime-component-names'
import provenanceJson from './generated/react-export-sources.provenance.json'

const blocksRoot = join(process.cwd(), 'packages/ship-fast-blocks')
const generatorPath =
  'packages/ship-fast-blocks/scripts/generate-react-export-sources.mjs'
const generatedHeader = `// This file is generated by ${generatorPath}.`

type GeneratedProvenance = {
  componentCount: number
  sectionComponentCount?: number
  components: Array<{ name: string; sourceFile: string }>
  generatedBy: string
  generatorVersion: number
  outputs: string[]
  sourceRoots: string[]
}

const provenance = provenanceJson as GeneratedProvenance

/**
 * Parse a generated TS file with a TypeScript AST and return the text of the
 * first leading comment (the generated-file header). This replaces brittle
 * `source.startsWith(header)` string matching with structural AST inspection.
 */
const firstLeadingComment = (filePath: string): string => {
  const source = readFileSync(join(blocksRoot, filePath), 'utf8')
  const sourceFile = ts.createSourceFile(
    filePath,
    source,
    ts.ScriptTarget.Latest,
    true,
    ts.ScriptKind.TS,
  )
  const firstStatement = sourceFile.statements[0]
  if (!firstStatement) return ''
  const ranges = ts.getLeadingCommentRanges(
    sourceFile.getFullText(),
    firstStatement.getFullStart(),
  )
  if (!ranges || ranges.length === 0) return ''
  const range = ranges[0]
  return sourceFile.getFullText().slice(range.pos, range.end)
}

describe('generated OpenUI artifact provenance', () => {
  it('records the generator, source roots, output files, and input component files', () => {
    expect(provenance.generatorVersion).toBe(1)
    expect(provenance.generatedBy).toBe(generatorPath)
    expect(provenance.sourceRoots).toEqual(['src/registry', 'src/capsules'])
    expect(provenance.outputs).toEqual([
      'src/generated/react-export-sources.json',
      'src/generated/react-export-sources.compressed.ts',
      'src/generated/block-source-files.compressed.ts',
      'src/generated/vendor-source-files.compressed.ts',
      'src/generated/runtime-component-loaders.ts',
      'src/generated/runtime-component-names.ts',
      'src/generated/runtime-section-component-names.ts',
      'src/generated/capsule-categories.ts',
      'src/generated/react-export-sources.provenance.json',
    ])
    expect(provenance.componentCount).toBe(provenance.components.length)
    expect(provenance.componentCount).toBeGreaterThan(1_000)
    // The exported runtime names (direct module import) must match the
    // provenance manifest exactly — no regex extraction from source text.
    expect(provenance.components.map(({ name }) => name)).toEqual([
      ...runtimeComponentNames,
    ])
    expect(provenance.components).toContainEqual({
      name: 'Stack',
      sourceFile: 'src/registry/primitives/layout.tsx',
    })

    for (const output of provenance.outputs) {
      expect(existsSync(join(blocksRoot, output))).toBe(true)
    }

    for (const { sourceFile } of provenance.components) {
      expect(sourceFile).toMatch(/^src\/(?:registry|capsules)\/.+\.tsx$/)
      expect(existsSync(join(blocksRoot, sourceFile))).toBe(true)
    }
  })

  it('marks generated TypeScript artifacts with the generator that owns them', () => {
    for (const output of [
      'src/generated/react-export-sources.compressed.ts',
      'src/generated/block-source-files.compressed.ts',
      'src/generated/vendor-source-files.compressed.ts',
      'src/generated/runtime-component-loaders.ts',
      'src/generated/runtime-component-names.ts',
      'src/generated/runtime-section-component-names.ts',
    ]) {
      const commentText = firstLeadingComment(output)
      expect(commentText).toBe(generatedHeader)
    }
  })
})
