import { existsSync, readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'

const blocksRoot = join(process.cwd(), 'packages/ship-fast-blocks')
const generatorPath =
  'packages/ship-fast-blocks/scripts/generate-react-export-sources.mjs'
const generatedHeader = `// This file is generated by ${generatorPath}.`

type GeneratedProvenance = {
  componentCount: number
  components: Array<{ name: string; sourceFile: string }>
  generatedBy: string
  generatorVersion: number
  outputs: string[]
  sourceRoots: string[]
}

const readGeneratedProvenance = (): GeneratedProvenance =>
  JSON.parse(
    readFileSync(
      join(blocksRoot, 'src/generated/react-export-sources.provenance.json'),
      'utf8',
    ),
  ) as GeneratedProvenance

const readRuntimeComponentNames = () => {
  const source = readFileSync(
    join(blocksRoot, 'src/generated/runtime-component-names.ts'),
    'utf8',
  )

  return [...source.matchAll(/^\s+['"]([^'"]+)['"],$/gm)].map(
    (match) => match[1],
  )
}

describe('generated OpenUI artifact provenance', () => {
  it('records the generator, source roots, output files, and input component files', () => {
    const provenance = readGeneratedProvenance()

    expect(provenance.generatorVersion).toBe(1)
    expect(provenance.generatedBy).toBe(generatorPath)
    expect(provenance.sourceRoots).toEqual(['src/registry', 'src/capsules'])
    expect(provenance.outputs).toEqual([
      'src/generated/react-export-sources.json',
      'src/generated/react-export-sources.compressed.ts',
      'src/generated/runtime-component-loaders.ts',
      'src/generated/runtime-component-names.ts',
      'src/generated/react-export-sources.provenance.json',
    ])
    expect(provenance.componentCount).toBe(provenance.components.length)
    expect(provenance.componentCount).toBeGreaterThan(1_000)
    expect(provenance.components.map(({ name }) => name)).toEqual(
      readRuntimeComponentNames(),
    )
    expect(provenance.components).toContainEqual({
      name: 'Stack',
      sourceFile: 'src/registry/primitives/layout.tsx',
    })

    for (const output of provenance.outputs) {
      expect(existsSync(join(blocksRoot, output))).toBe(true)
    }

    for (const { sourceFile } of provenance.components) {
      expect(sourceFile).toMatch(/^src\/(?:registry|capsules)\/.+\.tsx$/)
      expect(existsSync(join(blocksRoot, sourceFile))).toBe(true)
    }
  })

  it('marks generated TypeScript artifacts with the generator that owns them', () => {
    for (const output of [
      'src/generated/react-export-sources.compressed.ts',
      'src/generated/runtime-component-loaders.ts',
      'src/generated/runtime-component-names.ts',
    ]) {
      const source = readFileSync(join(blocksRoot, output), 'utf8')
      expect(source.startsWith(generatedHeader)).toBe(true)
    }
  })
})
