import { ConvexError, v } from 'convex/values'

import { mutation, query } from './_generated/server'
import type { Doc, Id } from './_generated/dataModel'
import type { MutationCtx } from './_generated/server'

const exportTarget = v.union(v.literal('html'), v.literal('react'), v.literal('next'))

const engineTaskStatus = v.union(
  v.literal('PENDING'),
  v.literal('IN_PROGRESS'),
  v.literal('DONE'),
  v.literal('FAILED'),
)

const engineTask = v.object({
  id: v.string(),
  label: v.string(),
  status: engineTaskStatus,
  filename: v.optional(v.string()),
  files: v.optional(v.array(v.string())),
})

const textEncoder = new TextEncoder()

const toHex = (bytes: ArrayBuffer): string =>
  Array.from(new Uint8Array(bytes), (byte) => byte.toString(16).padStart(2, '0')).join('')

const hashOwnerSecret = async (ownerSecret: string): Promise<string> =>
  toHex(await crypto.subtle.digest('SHA-256', textEncoder.encode(ownerSecret)))

const getUserId = async (ctx: MutationCtx) => {
  const identity = await ctx.auth.getUserIdentity()
  return identity?.subject
}

const escapeHtml = (value: string): string =>
  value
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#39;')

const renderInitialPreviewHtml = (prompt: string): string =>
  `<main style="font-family:Inter,system-ui,sans-serif;padding:48px;min-height:100vh;background:#f8fafc;color:#0f172a"><p style="font-size:12px;letter-spacing:.16em;text-transform:uppercase;color:#0891b2;font-weight:700">Generated by Ship Fast</p><h1 style="max-width:760px;font-size:44px;line-height:1.05;margin:16px 0 20px">${escapeHtml(prompt)}</h1><p style="max-width:680px;font-size:18px;line-height:1.7;color:#475569">This durable preview was written through self-hosted Convex. The GenUI engine will replace this placeholder with the full generated site pipeline.</p></main>`

const assertCanMutateSession = async (
  ctx: MutationCtx,
  session: { userId?: string; anonOwnerSecretHash?: string },
  anonymousOwnerSecret?: string,
) => {
  const userId = await getUserId(ctx)
  const anonymousOwnerSecretHash =
    anonymousOwnerSecret === undefined ? undefined : await hashOwnerSecret(anonymousOwnerSecret)
  const isUserOwner = session.userId !== undefined && session.userId === userId
  const isAnonymousOwner =
    session.userId === undefined &&
    session.anonOwnerSecretHash !== undefined &&
    session.anonOwnerSecretHash === anonymousOwnerSecretHash

  isUserOwner ||
    isAnonymousOwner ||
    (() => {
      throw new ConvexError({ code: 'FORBIDDEN', message: 'You do not own this session' })
    })()
}

const assertPrompt = (prompt: string): void => {
  prompt.trim().length > 0 ||
    (() => {
      throw new ConvexError({ code: 'INVALID_PROMPT', message: 'Prompt is required' })
    })()
}

const normalizeDeploymentSlug = (value: string): string =>
  value
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .replace(/-{2,}/g, '-')
    .slice(0, 63)

const createDefaultDeploymentSlug = (prompt: string, sessionId: string): string => {
  const fromPrompt = normalizeDeploymentSlug(prompt).split('-').slice(0, 4).join('-')
  const fallback = normalizeDeploymentSlug(sessionId).slice(0, 20)

  return fromPrompt || fallback || 'generated-site'
}

const createDeploymentUrl = (slug: string): string => `https://${slug}.ship-fast.io`

const serializeSession = (session: Doc<'sessions'>) => ({
  sessionId: session._id,
  userId: session.userId,
  canClaimAnonymous: session.userId === undefined && session.anonOwnerSecretHash !== undefined,
  prompt: session.prompt,
  status: session.status,
  preferredLanguage: session.preferredLanguage,
  preferredExportTarget: session.preferredExportTarget,
  isPrivate: session.isPrivate,
  previewVersion: session.previewVersion,
  createdAt: session.createdAt,
  updatedAt: session.updatedAt,
  errorCode: session.errorCode,
  errorMessage: session.errorMessage,
})

const toTaskStatus = (status: 'PENDING' | 'IN_PROGRESS' | 'DONE' | 'FAILED') =>
  ({
    PENDING: 'pending',
    IN_PROGRESS: 'running',
    DONE: 'succeeded',
    FAILED: 'failed',
  })[status] as 'pending' | 'running' | 'succeeded' | 'failed'

const toTaskKey = (engineTaskId: string): string => (engineTaskId === 'home.openui' ? 'homepage' : engineTaskId)

const upsertTask = async (
  ctx: MutationCtx,
  sessionId: Id<'sessions'>,
  task: {
    id: string
    label: string
    status: 'PENDING' | 'IN_PROGRESS' | 'DONE' | 'FAILED'
  },
  order: number,
  now: number,
) => {
  const taskKey = toTaskKey(task.id)
  const existingTask = await ctx.db
    .query('tasks')
    .withIndex('by_sessionId_taskKey', (index) => index.eq('sessionId', sessionId).eq('taskKey', taskKey))
    .first()

  existingTask === null
    ? await ctx.db.insert('tasks', {
        sessionId,
        taskKey,
        title: task.label,
        status: toTaskStatus(task.status),
        order,
        createdAt: now,
        updatedAt: now,
      })
    : await ctx.db.patch(existingTask._id, {
        title: task.label,
        status: toTaskStatus(task.status),
        order,
        updatedAt: now,
      })
}

const upsertSiteSpec = async (
  ctx: MutationCtx,
  sessionId: Id<'sessions'>,
  specJson: string | undefined,
  now: number,
) => {
  if (specJson === undefined) return

  const existingSpec = await ctx.db
    .query('siteSpecs')
    .withIndex('by_sessionId', (index) => index.eq('sessionId', sessionId))
    .first()

  existingSpec === null
    ? await ctx.db.insert('siteSpecs', {
        sessionId,
        specJson,
        createdAt: now,
        updatedAt: now,
      })
    : await ctx.db.patch(existingSpec._id, {
        specJson,
        updatedAt: now,
      })
}

const upsertGeneratedModule = async (
  ctx: MutationCtx,
  sessionId: Id<'sessions'>,
  source: string | undefined,
  now: number,
) => {
  if (source === undefined) return

  const existingModule = await ctx.db
    .query('generatedModules')
    .withIndex('by_sessionId_moduleKey', (index) => index.eq('sessionId', sessionId).eq('moduleKey', 'home'))
    .first()

  existingModule === null
    ? await ctx.db.insert('generatedModules', {
        sessionId,
        moduleKey: 'home',
        source,
        status: 'succeeded',
        createdAt: now,
        updatedAt: now,
      })
    : await ctx.db.patch(existingModule._id, {
        source,
        status: 'succeeded',
        updatedAt: now,
      })
}

export const create = mutation({
  args: {
    prompt: v.string(),
    preferredLanguage: v.string(),
    preferredExportTarget: exportTarget,
    isPrivate: v.boolean(),
    anonymousOwnerSecret: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    const prompt = args.prompt.trim()
    const userId = await getUserId(ctx)
    const anonOwnerSecretHash =
      userId === undefined && args.anonymousOwnerSecret !== undefined
        ? await hashOwnerSecret(args.anonymousOwnerSecret)
        : undefined
    const now = Date.now()

    assertPrompt(prompt)

    const sessionId = await ctx.db.insert('sessions', {
      userId,
      anonOwnerSecretHash,
      prompt,
      status: 'queued',
      preferredLanguage: args.preferredLanguage,
      preferredExportTarget: args.preferredExportTarget,
      isPrivate: args.isPrivate,
      previewVersion: 0,
      createdAt: now,
      updatedAt: now,
    })

    await ctx.db.insert('tasks', {
      sessionId,
      taskKey: 'homepage',
      title: 'Generate homepage',
      status: 'pending',
      order: 0,
      createdAt: now,
      updatedAt: now,
    })

    await ctx.db.insert('generationEvents', {
      sessionId,
      eventType: 'queued',
      message: 'Generation queued',
      createdAt: now,
    })

    return { sessionId }
  },
})

export const addGenerationEvent = mutation({
  args: {
    sessionId: v.id('sessions'),
    eventType: v.string(),
    message: v.string(),
  },
  handler: async (ctx, args) => {
    const now = Date.now()
    await ctx.db.insert('generationEvents', {
      sessionId: args.sessionId,
      eventType: args.eventType,
      message: args.message,
      createdAt: now,
    })

    if (args.eventType === 'status') {
      await ctx.db.patch(args.sessionId, {
        status: 'streaming',
        updatedAt: now,
      })
    }
  },
})

export const getWorkspace = query({
  args: {
    sessionId: v.id('sessions'),
  },
  handler: async (ctx, args) => {
    const session = await ctx.db.get(args.sessionId)
    const tasks = await ctx.db
      .query('tasks')
      .withIndex('by_sessionId', (index) => index.eq('sessionId', args.sessionId))
      .collect()
    const preview = await ctx.db
      .query('previews')
      .withIndex('by_sessionId_version', (index) => index.eq('sessionId', args.sessionId))
      .order('desc')
      .first()
    const deployment = await ctx.db
      .query('deployments')
      .withIndex('by_sessionId', (index) => index.eq('sessionId', args.sessionId))
      .first()
    const events = await ctx.db
      .query('generationEvents')
      .withIndex('by_sessionId_createdAt', (index) => index.eq('sessionId', args.sessionId))
      .order('desc')
      .take(12)

    return session === null
      ? null
      : {
          session: serializeSession(session),
          tasks: tasks.sort((left, right) => left.order - right.order),
          preview,
          deployment,
          events: events.reverse(),
        }
  },
})

export const getSessionReadiness = query({
  args: {
    lookup: v.string(),
  },
  handler: async (ctx, args) => {
    const sessionId = ctx.db.normalizeId('sessions', args.lookup)

    if (sessionId === null) return null

    const session = await ctx.db.get(sessionId)

    if (session === null) return null

    const tasks = await ctx.db
      .query('tasks')
      .withIndex('by_sessionId', (index) => index.eq('sessionId', sessionId))
      .collect()
    const preview = await ctx.db
      .query('previews')
      .withIndex('by_sessionId_version', (index) => index.eq('sessionId', sessionId))
      .order('desc')
      .first()
    const siteSpec = await ctx.db
      .query('siteSpecs')
      .withIndex('by_sessionId', (index) => index.eq('sessionId', sessionId))
      .first()
    const openUiModule = await ctx.db
      .query('generatedModules')
      .withIndex('by_sessionId_moduleKey', (index) => index.eq('sessionId', sessionId).eq('moduleKey', 'home'))
      .first()
    const sortedTasks = tasks.sort((left, right) => left.order - right.order)
    const done = sortedTasks.filter((task) => task.status === 'succeeded').length

    return {
      session: serializeSession(session),
      readiness: {
        homepageReady:
          session.status === 'homepage_ready' ||
          session.status === 'site_spec_ready' ||
          session.status === 'preview_ready' ||
          sortedTasks.some((task) => task.taskKey === 'homepage' && task.status === 'succeeded'),
        openuiReady:
          preview !== null ||
          (openUiModule !== null && openUiModule.status === 'succeeded'),
        siteSpecReady: siteSpec !== null || session.status === 'site_spec_ready' || session.status === 'preview_ready',
        done,
        taskCount: sortedTasks.length,
      },
    }
  },
})

export const getPublicPreview = query({
  args: {
    lookup: v.string(),
  },
  handler: async (ctx, args) => {
    const sessionId = ctx.db.normalizeId('sessions', args.lookup)
    const directSession = sessionId === null ? null : await ctx.db.get(sessionId)
    const deployment =
      directSession === null
        ? await ctx.db
            .query('deployments')
            .withIndex('by_slug', (index) => index.eq('slug', args.lookup))
            .first()
        : null
    const session = directSession ?? (deployment === null ? null : await ctx.db.get(deployment.sessionId))

    if (session === null || session.isPrivate) return null

    const preview = await ctx.db
      .query('previews')
      .withIndex('by_sessionId_version', (index) => index.eq('sessionId', session._id))
      .order('desc')
      .first()

    return preview === null
      ? {
          sessionId: session._id,
          slug: deployment?.slug,
          status: session.status,
          previewVersion: session.previewVersion,
          html: undefined,
        }
      : {
          sessionId: session._id,
          slug: deployment?.slug,
          status: session.status,
          previewVersion: preview.version,
          html: preview.html,
        }
  },
})

export const publishPreview = mutation({
  args: {
    sessionId: v.id('sessions'),
    anonymousOwnerSecret: v.optional(v.string()),
    requestedSlug: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    const session = await ctx.db.get(args.sessionId)
    const now = Date.now()

    session !== null ||
      (() => {
        throw new ConvexError({ code: 'NOT_FOUND', message: 'Session not found' })
      })()

    await assertCanMutateSession(ctx, session, args.anonymousOwnerSecret)

    await ctx.db.insert('generationEvents', {
      sessionId: args.sessionId,
      eventType: 'log',
      message: 'Persisting generated homepage',
      createdAt: now,
    })

    session.isPrivate === false ||
      (() => {
        throw new ConvexError({ code: 'PRIVATE_SESSION', message: 'Private sessions cannot be published' })
      })()

    session.status === 'preview_ready' ||
      (() => {
        throw new ConvexError({ code: 'PREVIEW_NOT_READY', message: 'Preview is not ready to publish' })
      })()

    const preview = await ctx.db
      .query('previews')
      .withIndex('by_sessionId_version', (index) => index.eq('sessionId', args.sessionId))
      .order('desc')
      .first()

    preview !== null ||
      (() => {
        throw new ConvexError({ code: 'PREVIEW_NOT_READY', message: 'Preview is not ready to publish' })
      })()

    const existingDeployment = await ctx.db
      .query('deployments')
      .withIndex('by_sessionId', (index) => index.eq('sessionId', args.sessionId))
      .first()

    if (existingDeployment !== null && args.requestedSlug === undefined) {
      return {
        sessionId: args.sessionId,
        slug: existingDeployment.slug,
        url: existingDeployment.url,
        status: existingDeployment.status,
      }
    }

    const slug = normalizeDeploymentSlug(
      args.requestedSlug ?? createDefaultDeploymentSlug(session.prompt, args.sessionId),
    )

    slug.length > 0 ||
      (() => {
        throw new ConvexError({ code: 'INVALID_SLUG', message: 'Deployment slug is required' })
      })()

    const existingBySlug = await ctx.db
      .query('deployments')
      .withIndex('by_slug', (index) => index.eq('slug', slug))
      .first()

    ;(existingBySlug === null || existingBySlug.sessionId === args.sessionId) ||
      (() => {
        throw new ConvexError({ code: 'SLUG_TAKEN', message: 'Deployment slug is already taken' })
      })()

    const url = createDeploymentUrl(slug)

    existingDeployment === null
      ? await ctx.db.insert('deployments', {
          sessionId: args.sessionId,
          slug,
          url,
          status: 'ready',
          createdAt: now,
          updatedAt: now,
        })
      : await ctx.db.patch(existingDeployment._id, {
          slug,
          url,
          status: 'ready',
          errorMessage: undefined,
          updatedAt: now,
        })

    await ctx.db.insert('generationEvents', {
      sessionId: args.sessionId,
      eventType: 'published',
      message: `Published preview to ${url}`,
      previewVersion: preview.version,
      createdAt: now,
    })

    return {
      sessionId: args.sessionId,
      slug,
      url,
      status: 'ready' as const,
    }
  },
})

export const completeMockGeneration = mutation({
  args: {
    sessionId: v.id('sessions'),
    anonymousOwnerSecret: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    const session = await ctx.db.get(args.sessionId)
    const now = Date.now()

    session !== null ||
      (() => {
        throw new ConvexError({ code: 'NOT_FOUND', message: 'Session not found' })
      })()

    await assertCanMutateSession(ctx, session, args.anonymousOwnerSecret)

    const homepageTask = await ctx.db
      .query('tasks')
      .withIndex('by_sessionId_taskKey', (index) =>
        index.eq('sessionId', args.sessionId).eq('taskKey', 'homepage'),
      )
      .first()
    const html = renderInitialPreviewHtml(session.prompt)

    homepageTask !== null &&
      (await ctx.db.patch(homepageTask._id, {
        status: 'succeeded',
        updatedAt: now,
      }))

    await ctx.db.insert('previews', {
      sessionId: args.sessionId,
      version: 1,
      html,
      source: 'generation',
      createdAt: now,
    })

    await ctx.db.insert('generationEvents', {
      sessionId: args.sessionId,
      eventType: 'preview_ready',
      message: 'Initial preview ready',
      previewVersion: 1,
      createdAt: now,
    })

    await ctx.db.patch(args.sessionId, {
      status: 'preview_ready',
      previewVersion: 1,
      updatedAt: now,
    })

    return { sessionId: args.sessionId, previewVersion: 1 }
  },
})

export const completeGeneration = mutation({
  args: {
    sessionId: v.id('sessions'),
    anonymousOwnerSecret: v.optional(v.string()),
    html: v.string(),
    siteSpecJson: v.optional(v.string()),
    openUiSource: v.optional(v.string()),
    tasks: v.array(engineTask),
  },
  handler: async (ctx, args) => {
    const session = await ctx.db.get(args.sessionId)
    const now = Date.now()

    session !== null ||
      (() => {
        throw new ConvexError({ code: 'NOT_FOUND', message: 'Session not found' })
      })()

    await assertCanMutateSession(ctx, session, args.anonymousOwnerSecret)

    await Promise.all(args.tasks.map((task, index) => upsertTask(ctx, args.sessionId, task, index, now)))
    await upsertSiteSpec(ctx, args.sessionId, args.siteSpecJson, now)
    await upsertGeneratedModule(ctx, args.sessionId, args.openUiSource, now)

    const previewVersion = session.previewVersion + 1

    await ctx.db.insert('previews', {
      sessionId: args.sessionId,
      version: previewVersion,
      html: args.html,
      source: 'generation',
      createdAt: now,
    })

    await ctx.db.insert('generationEvents', {
      sessionId: args.sessionId,
      eventType: 'preview_ready',
      message: 'Generated preview ready',
      previewVersion,
      createdAt: now,
    })

    await ctx.db.patch(args.sessionId, {
      status: 'preview_ready',
      previewVersion,
      updatedAt: now,
    })

    return { sessionId: args.sessionId, previewVersion }
  },
})

export const failGeneration = mutation({
  args: {
    sessionId: v.id('sessions'),
    anonymousOwnerSecret: v.optional(v.string()),
    message: v.string(),
  },
  handler: async (ctx, args) => {
    const session = await ctx.db.get(args.sessionId)
    const now = Date.now()

    session !== null ||
      (() => {
        throw new ConvexError({ code: 'NOT_FOUND', message: 'Session not found' })
      })()

    await assertCanMutateSession(ctx, session, args.anonymousOwnerSecret)

    const homepageTask = await ctx.db
      .query('tasks')
      .withIndex('by_sessionId_taskKey', (index) =>
        index.eq('sessionId', args.sessionId).eq('taskKey', 'homepage'),
      )
      .first()

    homepageTask !== null &&
      (await ctx.db.patch(homepageTask._id, {
        status: 'failed',
        errorMessage: args.message,
        updatedAt: now,
      }))

    await ctx.db.insert('generationEvents', {
      sessionId: args.sessionId,
      eventType: 'failed',
      message: args.message,
      createdAt: now,
    })

    await ctx.db.patch(args.sessionId, {
      status: 'failed',
      errorCode: 'GENERATION_FAILED',
      errorMessage: args.message,
      updatedAt: now,
    })

    return { sessionId: args.sessionId }
  },
})

export const claimAnonymous = mutation({
  args: {
    sessionId: v.id('sessions'),
    anonymousOwnerSecret: v.string(),
  },
  handler: async (ctx, args) => {
    const userId = await getUserId(ctx)
    const session = await ctx.db.get(args.sessionId)
    const anonymousOwnerSecretHash = await hashOwnerSecret(args.anonymousOwnerSecret)

    userId !== undefined ||
      (() => {
        throw new ConvexError({ code: 'AUTH_REQUIRED', message: 'Sign in to claim this session' })
      })()

    session !== null ||
      (() => {
        throw new ConvexError({ code: 'NOT_FOUND', message: 'Session not found' })
      })()

    session.userId === undefined ||
      (() => {
        throw new ConvexError({ code: 'ALREADY_OWNED', message: 'Session is already owned' })
      })()

    session.anonOwnerSecretHash === anonymousOwnerSecretHash ||
      (() => {
        throw new ConvexError({ code: 'FORBIDDEN', message: 'Invalid anonymous owner secret' })
      })()

    await ctx.db.patch(args.sessionId, {
      userId,
      anonOwnerSecretHash: undefined,
      updatedAt: Date.now(),
    })

    return { sessionId: args.sessionId }
  },
})

export const createExport = mutation({
  args: {
    sessionId: v.id('sessions'),
    anonymousOwnerSecret: v.optional(v.string()),
    target: exportTarget,
  },
  handler: async (ctx, args) => {
    const session = await ctx.db.get(args.sessionId)
    const now = Date.now()

    session !== null ||
      (() => {
        throw new ConvexError({ code: 'NOT_FOUND', message: 'Session not found' })
      })()

    await assertCanMutateSession(ctx, session, args.anonymousOwnerSecret)

    session.status === 'preview_ready' ||
      (() => {
        throw new ConvexError({ code: 'PREVIEW_NOT_READY', message: 'Preview is not ready to export' })
      })()

    const preview = await ctx.db
      .query('previews')
      .withIndex('by_sessionId_version', (index) => index.eq('sessionId', args.sessionId))
      .order('desc')
      .first()

    preview !== null ||
      (() => {
        throw new ConvexError({ code: 'PREVIEW_NOT_READY', message: 'Preview is not ready to export' })
      })()

    const existingExport = await ctx.db
      .query('exports')
      .withIndex('by_sessionId_target', (index) =>
        index.eq('sessionId', args.sessionId).eq('target', args.target),
      )
      .first()

    if (existingExport !== null && existingExport.status === 'ready') {
      return {
        exportId: existingExport._id,
        target: existingExport.target,
        status: existingExport.status,
        fileCount: existingExport.fileCount,
      }
    }

    const exportId =
      existingExport !== null
        ? existingExport._id
        : await ctx.db.insert('exports', {
            sessionId: args.sessionId,
            target: args.target,
            status: 'ready',
            artifactPath: `preview-${preview.version}.html`,
            fileCount: 1,
            requiresPayment: false,
            createdAt: now,
            updatedAt: now,
          })

    if (existingExport !== null) {
      await ctx.db.patch(exportId, {
        status: 'ready',
        artifactPath: `preview-${preview.version}.html`,
        fileCount: 1,
        errorMessage: undefined,
        updatedAt: now,
      })
    }

    await ctx.db.insert('generationEvents', {
      sessionId: args.sessionId,
      eventType: 'export_ready',
      message: `Export ready for ${args.target}`,
      previewVersion: preview.version,
      createdAt: now,
    })

    return {
      exportId,
      target: args.target,
      status: 'ready' as const,
      fileCount: 1,
    }
  },
})

export const getExport = query({
  args: {
    sessionId: v.id('sessions'),
    target: exportTarget,
  },
  handler: async (ctx, args) => {
    const exportRecord = await ctx.db
      .query('exports')
      .withIndex('by_sessionId_target', (index) =>
        index.eq('sessionId', args.sessionId).eq('target', args.target),
      )
      .first()

    return exportRecord === null
      ? null
      : {
          exportId: exportRecord._id,
          target: exportRecord.target,
          status: exportRecord.status,
          fileCount: exportRecord.fileCount,
          requiresPayment: exportRecord.requiresPayment,
          errorMessage: exportRecord.errorMessage,
          createdAt: exportRecord.createdAt,
          updatedAt: exportRecord.updatedAt,
        }
  },
})

export const createEdit = mutation({
  args: {
    sessionId: v.id('sessions'),
    anonymousOwnerSecret: v.optional(v.string()),
    editType: v.union(v.literal('text'), v.literal('ai_rewrite'), v.literal('chat')),
    targetLabel: v.optional(v.string()),
    beforeText: v.optional(v.string()),
    afterText: v.optional(v.string()),
    instruction: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    const session = await ctx.db.get(args.sessionId)
    const now = Date.now()

    session !== null ||
      (() => {
        throw new ConvexError({ code: 'NOT_FOUND', message: 'Session not found' })
      })()

    await assertCanMutateSession(ctx, session, args.anonymousOwnerSecret)

    const preview = await ctx.db
      .query('previews')
      .withIndex('by_sessionId_version', (index) => index.eq('sessionId', args.sessionId))
      .order('desc')
      .first()

    preview !== null ||
      (() => {
        throw new ConvexError({ code: 'PREVIEW_NOT_READY', message: 'Preview is not ready' })
      })()

    await ctx.db.insert('edits', {
      sessionId: args.sessionId,
      previewVersion: preview.version,
      editType: args.editType,
      targetLabel: args.targetLabel,
      beforeText: args.beforeText,
      afterText: args.afterText,
      instruction: args.instruction,
      createdAt: now,
      userId: session.userId,
    })

    return { sessionId: args.sessionId, previewVersion: preview.version }
  },
})

export const listEdits = query({
  args: {
    sessionId: v.id('sessions'),
  },
  handler: async (ctx, args) => {
    const edits = await ctx.db
      .query('edits')
      .withIndex('by_sessionId_createdAt', (index) => index.eq('sessionId', args.sessionId))
      .order('desc')
      .collect()

    return edits.map((edit) => ({
      editId: edit._id,
      editType: edit.editType,
      targetLabel: edit.targetLabel,
      beforeText: edit.beforeText,
      afterText: edit.afterText,
      instruction: edit.instruction,
      previewVersion: edit.previewVersion,
      createdAt: edit.createdAt,
      userId: edit.userId,
    }))
  },
})

export const sendChatMessage = mutation({
  args: {
    sessionId: v.id('sessions'),
    anonymousOwnerSecret: v.optional(v.string()),
    content: v.string(),
  },
  handler: async (ctx, args) => {
    const session = await ctx.db.get(args.sessionId)
    const now = Date.now()

    session !== null ||
      (() => {
        throw new ConvexError({ code: 'NOT_FOUND', message: 'Session not found' })
      })()

    await assertCanMutateSession(ctx, session, args.anonymousOwnerSecret)

    await ctx.db.insert('chatMessages', {
      sessionId: args.sessionId,
      role: 'user',
      content: args.content,
      createdAt: now,
    })

    return { sessionId: args.sessionId }
  },
})

export const listChatMessages = query({
  args: {
    sessionId: v.id('sessions'),
  },
  handler: async (ctx, args) => {
    const messages = await ctx.db
      .query('chatMessages')
      .withIndex('by_sessionId_createdAt', (index) => index.eq('sessionId', args.sessionId))
      .order('asc')
      .collect()

    return messages.map((msg) => ({
      messageId: msg._id,
      role: msg.role,
      content: msg.content,
      createdAt: msg.createdAt,
    }))
  },
})

export const createAnnotation = mutation({
  args: {
    sessionId: v.id('sessions'),
    anonymousOwnerSecret: v.optional(v.string()),
    annotationId: v.string(),
    agentationSessionKey: v.string(),
    comment: v.string(),
    elementLabel: v.string(),
    elementPath: v.string(),
    url: v.optional(v.string()),
    payloadJson: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    const session = await ctx.db.get(args.sessionId)
    const now = Date.now()

    session !== null ||
      (() => {
        throw new ConvexError({ code: 'NOT_FOUND', message: 'Session not found' })
      })()

    await assertCanMutateSession(ctx, session, args.anonymousOwnerSecret)

    await ctx.db.insert('agentationAnnotations', {
      sessionId: args.sessionId,
      annotationId: args.annotationId,
      agentationSessionKey: args.agentationSessionKey,
      comment: args.comment,
      elementLabel: args.elementLabel,
      elementPath: args.elementPath,
      url: args.url,
      payloadJson: args.payloadJson,
      createdAt: now,
      updatedAt: now,
    })

    return { sessionId: args.sessionId }
  },
})

export const upsertAnnotation = mutation({
  args: {
    sessionId: v.id('sessions'),
    anonymousOwnerSecret: v.optional(v.string()),
    annotationId: v.string(),
    agentationSessionKey: v.string(),
    comment: v.string(),
    elementLabel: v.string(),
    elementPath: v.string(),
    url: v.optional(v.string()),
    payloadJson: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    const session = await ctx.db.get(args.sessionId)
    const now = Date.now()

    session !== null ||
      (() => {
        throw new ConvexError({ code: 'NOT_FOUND', message: 'Session not found' })
      })()

    await assertCanMutateSession(ctx, session, args.anonymousOwnerSecret)

    const existing = await ctx.db
      .query('agentationAnnotations')
      .withIndex('by_sessionId_annotationId', (index) =>
        index.eq('sessionId', args.sessionId).eq('annotationId', args.annotationId),
      )
      .first()

    const payload = {
      agentationSessionKey: args.agentationSessionKey,
      comment: args.comment,
      elementLabel: args.elementLabel,
      elementPath: args.elementPath,
      url: args.url,
      payloadJson: args.payloadJson,
      updatedAt: now,
    }

    if (existing !== null) {
      await ctx.db.patch(existing._id, payload)
      return { sessionId: args.sessionId, annotationId: existing._id }
    }

    const annotationId = await ctx.db.insert('agentationAnnotations', {
      sessionId: args.sessionId,
      annotationId: args.annotationId,
      ...payload,
      createdAt: now,
    })

    return { sessionId: args.sessionId, annotationId }
  },
})

export const listAnnotations = query({
  args: {
    sessionId: v.id('sessions'),
  },
  handler: async (ctx, args) => {
    const annotations = await ctx.db
      .query('agentationAnnotations')
      .withIndex('by_sessionId_annotationId', (index) => index.eq('sessionId', args.sessionId))
      .collect()

    return annotations.map((ann) => ({
      annotationId: ann._id,
      agentationSessionKey: ann.agentationSessionKey,
      comment: ann.comment,
      elementLabel: ann.elementLabel,
      elementPath: ann.elementPath,
      url: ann.url,
      payloadJson: ann.payloadJson,
      createdAt: ann.createdAt,
      updatedAt: ann.updatedAt,
    }))
  },
})

export const deleteAnnotation = mutation({
  args: {
    sessionId: v.id('sessions'),
    anonymousOwnerSecret: v.optional(v.string()),
    annotationId: v.id('agentationAnnotations'),
  },
  handler: async (ctx, args) => {
    const session = await ctx.db.get(args.sessionId)

    session !== null ||
      (() => {
        throw new ConvexError({ code: 'NOT_FOUND', message: 'Session not found' })
      })()

    await assertCanMutateSession(ctx, session, args.anonymousOwnerSecret)

    const annotation = await ctx.db.get(args.annotationId)

    annotation !== null && annotation.sessionId === args.sessionId
      ? await ctx.db.delete(args.annotationId)
      : (() => {
          throw new ConvexError({ code: 'NOT_FOUND', message: 'Annotation not found for this session' })
        })()

    return { sessionId: args.sessionId }
  },
})

export const deleteAnnotationByAgentationId = mutation({
  args: {
    sessionId: v.id('sessions'),
    anonymousOwnerSecret: v.optional(v.string()),
    annotationId: v.string(),
  },
  handler: async (ctx, args) => {
    const session = await ctx.db.get(args.sessionId)

    session !== null ||
      (() => {
        throw new ConvexError({ code: 'NOT_FOUND', message: 'Session not found' })
      })()

    await assertCanMutateSession(ctx, session, args.anonymousOwnerSecret)

    const annotation = await ctx.db
      .query('agentationAnnotations')
      .withIndex('by_sessionId_annotationId', (index) =>
        index.eq('sessionId', args.sessionId).eq('annotationId', args.annotationId),
      )
      .first()

    if (annotation !== null) {
      await ctx.db.delete(annotation._id)
    }

    return { sessionId: args.sessionId }
  },
})

export const clearAnnotations = mutation({
  args: {
    sessionId: v.id('sessions'),
    anonymousOwnerSecret: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    const session = await ctx.db.get(args.sessionId)

    session !== null ||
      (() => {
        throw new ConvexError({ code: 'NOT_FOUND', message: 'Session not found' })
      })()

    await assertCanMutateSession(ctx, session, args.anonymousOwnerSecret)

    const annotations = await ctx.db
      .query('agentationAnnotations')
      .withIndex('by_sessionId_annotationId', (index) => index.eq('sessionId', args.sessionId))
      .collect()

    await Promise.all(annotations.map((annotation) => ctx.db.delete(annotation._id)))

    return { sessionId: args.sessionId }
  },
})

export const upsertCmsConfig = mutation({
  args: {
    sessionId: v.id('sessions'),
    anonymousOwnerSecret: v.optional(v.string()),
    projectId: v.optional(v.string()),
    dataset: v.optional(v.string()),
    configJson: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    const session = await ctx.db.get(args.sessionId)
    const now = Date.now()

    session !== null ||
      (() => {
        throw new ConvexError({ code: 'NOT_FOUND', message: 'Session not found' })
      })()

    await assertCanMutateSession(ctx, session, args.anonymousOwnerSecret)

    const existing = await ctx.db
      .query('cmsConfigs')
      .withIndex('by_sessionId', (index) => index.eq('sessionId', args.sessionId))
      .first()

    if (existing !== null) {
      await ctx.db.patch(existing._id, {
        projectId: args.projectId,
        dataset: args.dataset,
        configJson: args.configJson,
        status: 'ready',
        updatedAt: now,
      })
    } else {
      await ctx.db.insert('cmsConfigs', {
        sessionId: args.sessionId,
        status: 'ready',
        projectId: args.projectId,
        dataset: args.dataset,
        configJson: args.configJson,
        createdAt: now,
        updatedAt: now,
      })
    }

    return { sessionId: args.sessionId }
  },
})

export const getCmsConfig = query({
  args: {
    sessionId: v.id('sessions'),
  },
  handler: async (ctx, args) => {
    const config = await ctx.db
      .query('cmsConfigs')
      .withIndex('by_sessionId', (index) => index.eq('sessionId', args.sessionId))
      .first()

    return config === null
      ? null
      : {
          configId: config._id,
          status: config.status,
          projectId: config.projectId,
          dataset: config.dataset,
          configJson: config.configJson,
          errorMessage: config.errorMessage,
          createdAt: config.createdAt,
          updatedAt: config.updatedAt,
        }
  },
})

export const upsertCommerceConfig = mutation({
  args: {
    sessionId: v.id('sessions'),
    anonymousOwnerSecret: v.optional(v.string()),
    backendUrl: v.optional(v.string()),
    adminUrl: v.optional(v.string()),
    storefrontUrl: v.optional(v.string()),
    configJson: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    const session = await ctx.db.get(args.sessionId)
    const now = Date.now()

    session !== null ||
      (() => {
        throw new ConvexError({ code: 'NOT_FOUND', message: 'Session not found' })
      })()

    await assertCanMutateSession(ctx, session, args.anonymousOwnerSecret)

    const existing = await ctx.db
      .query('commerceConfigs')
      .withIndex('by_sessionId', (index) => index.eq('sessionId', args.sessionId))
      .first()

    if (existing !== null) {
      await ctx.db.patch(existing._id, {
        backendUrl: args.backendUrl,
        adminUrl: args.adminUrl,
        storefrontUrl: args.storefrontUrl,
        configJson: args.configJson,
        status: 'ready',
        updatedAt: now,
      })
    } else {
      await ctx.db.insert('commerceConfigs', {
        sessionId: args.sessionId,
        status: 'ready',
        backendUrl: args.backendUrl,
        adminUrl: args.adminUrl,
        storefrontUrl: args.storefrontUrl,
        configJson: args.configJson,
        createdAt: now,
        updatedAt: now,
      })
    }

    return { sessionId: args.sessionId }
  },
})

export const getCommerceConfig = query({
  args: {
    sessionId: v.id('sessions'),
  },
  handler: async (ctx, args) => {
    const config = await ctx.db
      .query('commerceConfigs')
      .withIndex('by_sessionId', (index) => index.eq('sessionId', args.sessionId))
      .first()

    return config === null
      ? null
      : {
          configId: config._id,
          status: config.status,
          backendUrl: config.backendUrl,
          adminUrl: config.adminUrl,
          storefrontUrl: config.storefrontUrl,
          productCount: config.productCount,
          configJson: config.configJson,
          errorMessage: config.errorMessage,
          createdAt: config.createdAt,
          updatedAt: config.updatedAt,
        }
  },
})

export const listPublicSessions = query({
  args: {
    limit: v.optional(v.number()),
  },
  handler: async (ctx, args) => {
    const limit = args.limit ?? 20
    const sessions = await ctx.db
      .query('sessions')
      .withIndex('by_public_createdAt', (index) => index.eq('isPrivate', false))
      .order('desc')
      .collect()

    return sessions.slice(0, limit).map((session) => ({
      sessionId: session._id,
      prompt: session.prompt,
      status: session.status,
      previewVersion: session.previewVersion,
      createdAt: session.createdAt,
    }))
  },
})
