import { strFromU8, unzipSync } from 'fflate'

import { isUnsafePublicPreviewHtml } from '../../../../convex/lib/openui_error_html'
import {
  createHtmlExportFiles,
  extractExportMetadata,
} from './html-export-files'
import type { BuiltExport, OpenUIExportInput } from './openui-export-types'

function readGenUIExportMetadata(
  siteSpecJson: string | undefined,
): Record<string, unknown> | null {
  if (!siteSpecJson) return null
  try {
    const parsed = JSON.parse(siteSpecJson) as { genui?: unknown }
    return parsed.genui !== null &&
      typeof parsed.genui === 'object' &&
      !Array.isArray(parsed.genui)
      ? (parsed.genui as Record<string, unknown>)
      : null
  } catch {
    return null
  }
}

function withGenUIExportMetadata(
  input: OpenUIExportInput,
  files: Record<string, string>,
): Record<string, string> {
  const genui = readGenUIExportMetadata(input.siteSpecJson)
  const hasExplicitAdminPolicy =
    genui?.adminPolicy !== null &&
    typeof genui?.adminPolicy === 'object' &&
    !Array.isArray(genui.adminPolicy)
  if (input.syncSecret && !hasExplicitAdminPolicy) return files

  const supportsAdminModule =
    input.target === 'react' ||
    input.target === 'next' ||
    (input.target === 'lakebed' && genui !== null)
  if (!supportsAdminModule) return files

  // Always include admin wiring — use empty genui fallback when no genui
  // metadata is present so the admin gate uses a default owner email.
  const effectiveGenui = genui ?? {}
  const wiredFiles = withAdminAccessWiring(input, files, effectiveGenui)
  return {
    ...wiredFiles,
    'src/ship-fast-admin.ts': createAdminTypescriptModule(effectiveGenui),
  }
}

function readAdminPolicy(
  genui: Record<string, unknown>,
): Record<string, unknown> {
  const policy = genui.adminPolicy
  return policy !== null && typeof policy === 'object' && !Array.isArray(policy)
    ? (policy as Record<string, unknown>)
    : {}
}

function readAdminEmails(genui: Record<string, unknown>): string[] {
  const policy = readAdminPolicy(genui)
  const values = Array.isArray(policy.adminEmails)
    ? policy.adminEmails
    : typeof policy.ownerEmail === 'string'
      ? [policy.ownerEmail]
      : typeof genui.ownerEmail === 'string'
        ? [genui.ownerEmail]
        : []
  const emails = [
    ...new Set(
      values
        .filter((value): value is string => typeof value === 'string')
        .map((value) => value.trim().toLowerCase())
        .filter((value) => value.includes('@')),
    ),
  ]
  // Always provide a default owner email so the admin gate is usable
  // even when no genui metadata is present in the site spec.
  return emails.length > 0 ? emails : ['owner@ship-fast.local']
}

function slugifyRoute(value: string): string {
  return (
    value
      .trim()
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '') || 'page'
  )
}

function readAdminRoutes(
  genui: Record<string, unknown>,
): Array<{ label: string; path: string }> {
  const manifest = genui.openuiManifest
  const pages =
    manifest !== null &&
    typeof manifest === 'object' &&
    !Array.isArray(manifest) &&
    Array.isArray((manifest as { pages?: unknown }).pages)
      ? (manifest as { pages: unknown[] }).pages
      : []
  const manifestRoutes = pages
    .filter(
      (page): page is { id?: string; label?: string; component?: string } =>
        page !== null && typeof page === 'object',
    )
    .filter((page) =>
      [page.id, page.label, page.component].some(
        (value) => typeof value === 'string' && /admin/i.test(value),
      ),
    )
    .map((page) => {
      const label = typeof page.label === 'string' ? page.label : 'Admin'
      return { label, path: `/${slugifyRoute(label)}` }
    })

  return manifestRoutes.length > 0
    ? manifestRoutes
    : [{ label: 'Admin', path: '/admin' }]
}

function createAdminTypescriptModule(genui: Record<string, unknown>): string {
  const adminPolicy = readAdminPolicy(genui)
  const adminEmails = readAdminEmails(genui)
  return `// Generated by Ship Fast. Do not hand-edit.
export const shipFastAdminPolicy = ${JSON.stringify(adminPolicy, null, 2)};
export const shipFastAdminEmails: readonly string[] = ${JSON.stringify(adminEmails, null, 2)};

export function assertShipFastAdminAccess(email: string) {
  const normalized = String(email || '').trim().toLowerCase();
  if (!normalized || !shipFastAdminEmails.includes(normalized)) {
    throw new Error('Ship Fast admin access denied for this email.');
  }
  return { email: normalized, role: normalized === shipFastAdminEmails[0] ? 'owner' : 'editor' };
}
`
}

function createAdminGateModule(genui: Record<string, unknown>): string {
  const routes = readAdminRoutes(genui)
  const routeLabels = [
    ...new Set(routes.map((route) => route.label.trim().toLowerCase())),
  ]
  const routePaths = [
    ...new Set(routes.map((route) => route.path.trim().toLowerCase())),
  ]

  return `'use client'

import { useMemo, useState } from 'react'
import type { FormEvent, ReactNode } from 'react'
import { assertShipFastAdminAccess, shipFastAdminEmails } from '../ship-fast-admin'

const adminRouteLabels = ${JSON.stringify(routeLabels, null, 2)} as readonly string[]
const adminRoutePaths = ${JSON.stringify(routePaths, null, 2)} as readonly string[]

const normalize = (value: string | undefined) => String(value || '').trim().toLowerCase()

export function isShipFastAdminRoute(label?: string, path?: string) {
  return adminRouteLabels.includes(normalize(label)) || adminRoutePaths.includes(normalize(path))
}

export function ShipFastAdminGate({
  children,
  routeLabel = 'Admin',
}: {
  children: ReactNode
  routeLabel?: string
}) {
  const firstAdminEmail = shipFastAdminEmails[0] ?? ''
  const [email, setEmail] = useState(() => {
    if (typeof window === 'undefined') return firstAdminEmail
    return window.localStorage.getItem('shipFastAdminEmail') ?? firstAdminEmail
  })
  const [submittedEmail, setSubmittedEmail] = useState(() => {
    if (typeof window === 'undefined') return ''
    return window.localStorage.getItem('shipFastAdminEmail') ?? ''
  })
  const [error, setError] = useState('')

  const access = useMemo(() => {
    if (shipFastAdminEmails.length === 0) return { email: '', role: 'owner' }
    try {
      return assertShipFastAdminAccess(submittedEmail)
    } catch {
      return null
    }
  }, [submittedEmail])

  if (access) return <>{children}</>

  const onSubmit = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault()
    try {
      const result = assertShipFastAdminAccess(email)
      if (typeof window !== 'undefined') {
        window.localStorage.setItem('shipFastAdminEmail', result.email)
      }
      setSubmittedEmail(result.email)
      setError('')
    } catch (cause) {
      setError(cause instanceof Error ? cause.message : 'Admin access denied.')
    }
  }

  return (
    <main style={{ minHeight: '100vh', display: 'grid', placeItems: 'center', padding: 24, fontFamily: 'Inter, system-ui, sans-serif', background: '#0f172a', color: '#f8fafc' }}>
      <form onSubmit={onSubmit} style={{ width: '100%', maxWidth: 420, border: '1px solid rgba(148, 163, 184, 0.35)', borderRadius: 16, padding: 24, background: 'rgba(15, 23, 42, 0.92)', boxShadow: '0 24px 80px rgba(0,0,0,0.35)' }}>
        <p style={{ margin: 0, fontSize: 13, color: '#93c5fd', fontWeight: 700, letterSpacing: '0.08em', textTransform: 'uppercase' }}>Ship Fast Admin</p>
        <h1 style={{ margin: '10px 0 8px', fontSize: 28, lineHeight: 1.1 }}>Verify access to {routeLabel}</h1>
        <p style={{ margin: '0 0 20px', color: '#cbd5e1', lineHeight: 1.5 }}>Use the owner email baked into this export to open the generated admin area.</p>
        <label style={{ display: 'grid', gap: 8, fontSize: 13, color: '#cbd5e1' }}>
          Email
          <input value={email} onChange={(event) => setEmail(event.target.value)} type="email" autoComplete="email" placeholder="owner@example.com" style={{ border: '1px solid rgba(148, 163, 184, 0.45)', borderRadius: 10, padding: '12px 14px', background: '#020617', color: '#f8fafc' }} />
        </label>
        {error ? <p style={{ margin: '12px 0 0', color: '#fca5a5', fontSize: 13 }}>{error}</p> : null}
        <button type="submit" style={{ width: '100%', marginTop: 18, border: 0, borderRadius: 10, padding: '12px 14px', background: '#3b82f6', color: '#fff', fontWeight: 700, cursor: 'pointer' }}>Open admin</button>
      </form>
    </main>
  )
}
`
}

function wireReactAdminAccess(
  files: Record<string, string>,
  genui: Record<string, unknown>,
): Record<string, string> {
  const app = files['src/App.tsx']
  if (!app) return files
  const withImport = app.includes("from './lib/ship-fast-admin-gate'")
    ? app
    : app.replace(
        /(^import .* from 'react-router-dom'\n)/m,
        "$1import { isShipFastAdminRoute, ShipFastAdminGate } from './lib/ship-fast-admin-gate'\n",
      )
  const wiredApp = withImport.replace(
    /element=\{<([A-Za-z0-9_]+)(?: \{\.\.\.\1Route\.props\})? \/>\}/g,
    (_source, componentName) =>
      `element={isShipFastAdminRoute(${componentName}Route.label, ${componentName}Route.path) ? (
          <ShipFastAdminGate routeLabel={${componentName}Route.label}>
            <${componentName} />
          </ShipFastAdminGate>
        ) : (
          <${componentName} />
        )}`,
  )

  // Add /admin route to the routes data if it doesn't exist
  const pagesData = files['src/data/pages.ts'] ?? ''
  const hasAdminRoute = /['"]\/admin['"]/.test(pagesData)
  let updatedPagesData = pagesData
  if (!hasAdminRoute) {
    updatedPagesData = pagesData.replace(
      /(\];\s*$)/m,
      `  { label: 'Admin', path: '/admin', component: 'AdminPage', props: {} },\n$1`,
    )
  }

  return {
    ...files,
    'src/App.tsx': wiredApp,
    'src/data/pages.ts': updatedPagesData,
    'src/lib/ship-fast-admin-gate.tsx': createAdminGateModule(genui),
  }
}

function routeFileForPath(path: string): string {
  return path === '/'
    ? 'app/page.tsx'
    : `app/${path.replace(/^\//, '')}/page.tsx`
}

function nextImportPathForRouteFile(file: string): string {
  return file === 'app/page.tsx'
    ? '../src/lib/ship-fast-admin-gate'
    : '../../src/lib/ship-fast-admin-gate'
}

function wireNextAdminAccess(
  files: Record<string, string>,
  genui: Record<string, unknown>,
): Record<string, string> {
  const nextFiles = { ...files }
  const adminRoutes = readAdminRoutes(genui)
  for (const route of adminRoutes) {
    const file = routeFileForPath(route.path)
    const source = nextFiles[file]
    if (!source) continue
    const importPath = nextImportPathForRouteFile(file)
    const withImport = source.includes('ShipFastAdminGate')
      ? source
      : `import { ShipFastAdminGate } from '${importPath}'\n${source}`
    // Wrap the page's rendered component in <ShipFastAdminGate>. The page
    // is a server component that renders a client component inside a fragment.
    // Format after prettier: return ( <> <ComponentName /> ... </> )
    nextFiles[file] = withImport.replace(
      /(<[A-Za-z0-9_]+)(\s*\/>)/,
      `<ShipFastAdminGate routeLabel=${JSON.stringify(route.label)}>\n      $1$2\n    </ShipFastAdminGate>`,
    )
  }
  // If no admin route page exists yet, create a standalone /admin page
  const adminFile = routeFileForPath('/admin')
  if (!nextFiles[adminFile]) {
    const importPath = nextImportPathForRouteFile(adminFile)
    nextFiles[adminFile] = `import { ShipFastAdminGate } from '${importPath}'

export default function Page() {
  return <ShipFastAdminGate routeLabel="Admin"><p>Admin</p></ShipFastAdminGate>
}
`
  }
  return {
    ...nextFiles,
    'src/lib/ship-fast-admin-gate.tsx': createAdminGateModule(genui),
  }
}

function withAdminAccessWiring(
  input: OpenUIExportInput,
  files: Record<string, string>,
  genui: Record<string, unknown>,
): Record<string, string> {
  if (input.target === 'react') return wireReactAdminAccess(files, genui)
  if (input.target === 'next') return wireNextAdminAccess(files, genui)
  return files
}

function unzipTextFiles(body: Uint8Array) {
  return Object.fromEntries(
    Object.entries(unzipSync(body)).map(([path, value]) => [
      path,
      strFromU8(value),
    ]),
  )
}

export async function buildOpenUIArtifactFiles(input: OpenUIExportInput) {
  if (input.target === 'html') {
    const {
      buildOpenUIHtmlExport,
      isUsablePreviewHtml,
      neutralizeGeneratedHtmlRuntimeMarkers,
    } = await import('./openui-html-export-builder')
    const download = await buildOpenUIHtmlExport({
      ...input,
      includeBadge: input.includeBadge ?? false,
    })
    if (typeof download?.body === 'string') {
      const artifactBody = isUsablePreviewHtml(input.previewHtml)
        ? download.body
        : neutralizeGeneratedHtmlRuntimeMarkers(download.body)
      const artifactDownload = { ...download, body: artifactBody }
      const files = createHtmlExportFiles(
        input.sessionId,
        'html',
        artifactBody,
        {
          includeBadge: input.includeBadge ?? false,
        },
      )
      files['README.md'] = `# Static website

Open \`index.html\` in a browser or serve this directory with any static file server.
`
      return {
        files: withGenUIExportMetadata(input, files),
        download: artifactDownload,
      }
    }
    throw new Error('HTML export did not produce an HTML document')
  }

  if (input.target === 'lakebed') {
    const { buildOpenUILakebedProjectFiles } =
      await import('./openui-lakebed-export-builder')
    const project = await buildOpenUILakebedProjectFiles(input, {
      useEnvironmentSyncSecret: true,
    })
    return { files: withGenUIExportMetadata(input, project.files) }
  }

  const { buildOpenUIExport } = await import('./openui-export-builder')
  const download = await buildOpenUIExport(input)
  if (typeof download.body === 'string') {
    throw new Error(`${input.target} export did not produce a ZIP artifact`)
  }

  return {
    files: withGenUIExportMetadata(input, unzipTextFiles(download.body)),
    download,
  }
}

export async function buildDownloadFromArtifactFiles(
  input: OpenUIExportInput,
  files: Record<string, string>,
  prebuiltDownload?: BuiltExport,
) {
  if (prebuiltDownload !== undefined) return prebuiltDownload

  if (input.target === 'html') {
    // Never fall back to a handoff/error preview document.
    const safePreviewHtml =
      input.previewHtml !== undefined &&
      !isUnsafePublicPreviewHtml(input.previewHtml)
        ? input.previewHtml
        : undefined
    return {
      body: files['index.html'] ?? safePreviewHtml ?? input.source,
      contentType: 'text/html; charset=utf-8',
      filename: 'index.html',
      fileCount: 1,
    }
  }

  const { zipSync, strToU8 } = await import('fflate')
  const slug =
    input.target === 'lakebed'
      ? `ship-fast-${input.sessionId}`
      : extractExportMetadata(input.previewHtml ?? input.source)
          .title.trim()
          .toLowerCase()
          .replace(/[^a-z0-9]+/g, '-')
          .replace(/^-+|-+$/g, '')
          .slice(0, 60) || 'ship-fast-export'

  return {
    body: zipSync(
      Object.fromEntries(
        Object.entries(files).map(([path, source]) => [path, strToU8(source)]),
      ),
    ),
    contentType: 'application/zip',
    filename: `${slug}-${input.target}.zip`,
    fileCount: Object.keys(files).length,
  }
}
