import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { join, relative } from 'node:path'
import { brotliCompressSync, constants } from 'node:zlib'
import { fileURLToPath, pathToFileURL } from 'node:url'
import prettier from 'prettier'

const blocksRoot = join(fileURLToPath(new URL('..', import.meta.url)))
const repoRoot = join(blocksRoot, '..', '..')
const outFile = join(
  blocksRoot,
  'src',
  'generated',
  'lakebed-export-deps.compressed.ts',
)
const reactExportSourcesFile = join(
  blocksRoot,
  'src',
  'generated',
  'react-export-sources.json',
)
const generatorPath =
  'packages/ship-fast-blocks/scripts/generate-lakebed-export-deps.ts'
const isCheckMode = process.argv.includes('--check')
const priorityComponentNames = new Set([
  'AuthNavbar',
  'AuthHero',
  'AuthFeatures',
  'AuthCta',
  'AuthFooter',
  'PageSwitch',
  'StateText',
  'StateButton',
  'StateInput',
])

const formatGeneratedSource = async (path: string, source: string) => {
  const config = await prettier.resolveConfig(path)
  return await prettier.format(source, { ...config, filepath: path })
}

const loadManifest = async () => {
  const modulePath = join(
    repoRoot,
    'src',
    'features',
    'exports',
    'services',
    'openui-lakebed-export-builder.ts',
  )
  const module = await import(pathToFileURL(modulePath).href)
  const buildManifest = module.buildLakebedExportDependencyManifestForGenerator
  if (typeof buildManifest !== 'function') {
    throw new Error('Lakebed dependency manifest generator API is missing')
  }
  return buildManifest(readDefaultComponentNames())
}

const readDefaultComponentNames = () => {
  const source: unknown = JSON.parse(
    readFileSync(reactExportSourcesFile, 'utf8'),
  )
  if (!source || typeof source !== 'object' || Array.isArray(source)) {
    throw new Error('React export source manifest is missing or invalid')
  }
  return Object.entries(source)
    .flatMap(([componentName, entry]) => {
      if (!entry || typeof entry !== 'object' || Array.isArray(entry)) return []
      const componentSource = 'source' in entry ? entry.source : null
      if (typeof componentSource !== 'string') return []
      return priorityComponentNames.has(componentName) ? [componentName] : []
    })
    .sort()
}

const writeGeneratedFile = async () => {
  const manifest = await loadManifest()
  const json = `${JSON.stringify(manifest, null, 2)}\n`
  const compressed = brotliCompressSync(Buffer.from(json), {
    params: { [constants.BROTLI_PARAM_QUALITY]: 11 },
  }).toString('base64')
  const source = await formatGeneratedSource(
    outFile,
    `// This file is generated by ${generatorPath}.
export const lakebedExportDepsEncoding = 'br+base64' as const
export const lakebedExportDepsBase64 = '${compressed}' as const
`,
  )

  if (isCheckMode) {
    if (!existsSync(outFile) || readFileSync(outFile, 'utf8') !== source) {
      throw new Error(
        `Generated Lakebed export dependency manifest is out of date. Run bun run generate:lakebed-export-deps.\n- ${relative(blocksRoot, outFile)}`,
      )
    }
    console.log('Generated Lakebed export dependency manifest is current')
    return
  }

  writeFileSync(outFile, source)
  console.log(
    `lakebed-export-deps.compressed.ts regenerated: ${Object.keys(manifest.components).length} components, ${Object.keys(manifest.files).length} files`,
  )
}

await writeGeneratedFile()
