import { ConvexError } from 'convex/values'

import type { Id } from '../_generated/dataModel'
import type { MutationCtx } from '../_generated/server'
import { assertCanMutateSession } from './session_access_helpers'
import { upsertSessionAiCapsule } from './session_ai_capsule_helpers'

export type ApplySectionEditInput = {
  sessionId: Id<'sessions'>
  anonymousOwnerSecret?: string
  /** For HTML sessions: the full replacement preview.html. */
  replacementHtml?: string
  /** For OpenUI sessions: the patched OpenUI source (with AI capsule reference). */
  replacementOpenUiSource?: string
  /** For OpenUI sessions: the AI capsule to store. */
  aiCapsule?: {
    capsuleName: string
    parentCapsule: string
    compiledJs: string
    description: string
  }
  /** User's prompt for this edit. */
  instruction: string
}

/**
 * Apply an AI section edit to the session's artifacts: patch preview.html +
 * homeModule.source, bump previewVersion + updatedAt, record the edit, and
 * (for OpenUI) store the AI capsule.
 */
export const applySectionEditToArtifacts = async (
  ctx: MutationCtx,
  args: ApplySectionEditInput,
  now = Date.now(),
) => {
  const session = await ctx.db.get(args.sessionId)

  if (session === null) {
    throw new ConvexError({
      code: 'NOT_FOUND',
      message: 'Session not found',
    })
  }

  await assertCanMutateSession(ctx, session, args.anonymousOwnerSecret)

  // Fetch current artifacts
  const [homeModule, latestPreview] = await Promise.all([
    ctx.db
      .query('generatedModules')
      .withIndex('by_sessionId_moduleKey', (index) =>
        index.eq('sessionId', args.sessionId).eq('moduleKey', 'home'),
      )
      .first(),
    ctx.db
      .query('previews')
      .withIndex('by_sessionId_version', (index) =>
        index.eq('sessionId', args.sessionId),
      )
      .order('desc')
      .first(),
  ])

  if (latestPreview === null) {
    throw new ConvexError({
      code: 'PREVIEW_NOT_READY',
      message: 'Preview is not ready',
    })
  }

  const nextPreviewVersion = latestPreview.version + 1

  // Determine the new preview HTML and OpenUI source
  let newPreviewHtml = latestPreview.html
  let newOpenUiSource = homeModule?.source

  if (args.replacementHtml !== undefined) {
    // HTML session: replacement is the full page HTML
    newPreviewHtml = args.replacementHtml
    if (homeModule !== null) {
      newOpenUiSource = args.replacementHtml
      await ctx.db.patch(homeModule._id, {
        source: args.replacementHtml,
        status: 'succeeded',
        errorMessage: undefined,
        updatedAt: now,
      })
    }
  } else if (args.replacementOpenUiSource !== undefined) {
    // OpenUI session: patch the source, keep preview.html as-is
    // (the OpenUIViewer will re-render from source on remount)
    newOpenUiSource = args.replacementOpenUiSource
    if (homeModule !== null) {
      await ctx.db.patch(homeModule._id, {
        source: args.replacementOpenUiSource,
        status: 'succeeded',
        errorMessage: undefined,
        updatedAt: now,
      })
    }
    // For OpenUI, the preview.html is regenerated by the client on remount.
    // We store the patched source as the preview's openUiSource for reference.
    newPreviewHtml = latestPreview.html
  }

  // Store the AI capsule (OpenUI sessions only)
  if (args.aiCapsule) {
    await upsertSessionAiCapsule(ctx, {
      sessionId: args.sessionId,
      capsuleName: args.aiCapsule.capsuleName,
      parentCapsule: args.aiCapsule.parentCapsule,
      compiledJs: args.aiCapsule.compiledJs,
      description: args.aiCapsule.description,
    })
  }

  // Insert new preview version
  await ctx.db.insert('previews', {
    sessionId: args.sessionId,
    version: nextPreviewVersion,
    html: newPreviewHtml,
    openUiSource: newOpenUiSource,
    siteSpecJson: latestPreview.siteSpecJson,
    source: 'edit',
    createdAt: now,
  })

  // Bump session preview version
  await ctx.db.patch(args.sessionId, {
    previewVersion: nextPreviewVersion,
    updatedAt: now,
  })

  // Record edit
  await ctx.db.insert('edits', {
    sessionId: args.sessionId,
    previewVersion: nextPreviewVersion,
    editType: 'ai_rewrite',
    instruction: args.instruction,
    afterHtml: args.replacementHtml,
    createdAt: now,
    userId: session.userId,
  })

  // Emit preview reload event
  await ctx.db.insert('generationEvents', {
    sessionId: args.sessionId,
    eventType: 'preview_reload',
    message: 'AI section edit applied',
    previewVersion: nextPreviewVersion,
    createdAt: now,
  })

  return {
    sessionId: args.sessionId,
    previewVersion: nextPreviewVersion,
    saved: true,
  }
}
