import { execFileSync } from 'node:child_process'
import { mkdirSync, rmSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

import {
  changeGroups,
  classifyChangedPath,
  readChangeScope,
  type GitStatusEntry,
} from './verify-change-groups'

export const defaultReviewBundleDir = '.quality-review-groups'

type ReviewGroupBundle = {
  entries: GitStatusEntry[]
  group: (typeof changeGroups)[number]
}

type GitDiffRunner = (args: string[]) => string

function readStatusEntries() {
  return readChangeScope().entries
}

export function groupStatusEntries(entries: GitStatusEntry[]) {
  const bundles = new Map<string, ReviewGroupBundle>()
  const unclassified: string[] = []

  for (const group of changeGroups) {
    bundles.set(group.id, { entries: [], group })
  }

  for (const entry of entries) {
    const group = classifyChangedPath(entry.path)
    if (!group) {
      unclassified.push(entry.path)
      continue
    }

    bundles.get(group.id)?.entries.push(entry)
  }

  if (unclassified.length > 0) {
    throw new Error(
      `Cannot export review bundles with unclassified files:\n- ${unclassified.join('\n- ')}`,
    )
  }

  return [...bundles.values()].filter((bundle) => bundle.entries.length > 0)
}

function runGitDiff(args: string[]) {
  try {
    return execFileSync('git', args, {
      encoding: 'utf8',
      maxBuffer: 256 * 1024 * 1024,
    })
  } catch (error) {
    const result = error as { status?: number; stdout?: Buffer | string }
    if (result.status === 1 && result.stdout !== undefined) {
      return result.stdout.toString()
    }
    throw error
  }
}

export function renderFileList(bundle: ReviewGroupBundle) {
  return `${bundle.entries.map((entry) => `${entry.status} ${entry.path}`).join('\n')}\n`
}

export function renderReviewBundleReadme(bundles: ReviewGroupBundle[]) {
  const lines = [
    '# Review Group Bundles',
    '',
    'Generated by `bun scripts/export-review-groups.ts`.',
    'This directory is intentionally ignored by git and can be regenerated from the current dirty tree.',
    '',
    'Each group has:',
    '',
    '- `<group>.files.txt`: status-prefixed file list',
    '- `<group>.patch`: tracked diff plus untracked-file diffs',
    '',
    '## Groups',
    '',
  ]

  for (const bundle of bundles) {
    lines.push(
      `- ${bundle.group.title}: ${bundle.entries.length} file(s)`,
      `  - ${bundle.group.id}.files.txt`,
      `  - ${bundle.group.id}.patch`,
    )
  }

  return `${lines.join('\n')}\n`
}

export function renderGroupPatch(
  bundle: ReviewGroupBundle,
  diffRunner: GitDiffRunner = runGitDiff,
  baseRef: string | null = null,
) {
  const trackedPaths = bundle.entries
    .filter((entry) => entry.status !== '??')
    .map((entry) => entry.path)
  const untrackedPaths = bundle.entries
    .filter((entry) => entry.status === '??')
    .map((entry) => entry.path)

  const parts = [`# ${bundle.group.title}\n`]

  if (baseRef && trackedPaths.length > 0) {
    parts.push(
      diffRunner([
        'diff',
        '--binary',
        `${baseRef}...HEAD`,
        '--',
        ...trackedPaths,
      ]),
    )
  }

  if (trackedPaths.length > 0) {
    parts.push(diffRunner(['diff', '--binary', 'HEAD', '--', ...trackedPaths]))
  }

  for (const path of untrackedPaths) {
    parts.push(
      diffRunner(['diff', '--no-index', '--binary', '--', '/dev/null', path]),
    )
  }

  return `${parts.join('\n').trimEnd()}\n`
}

export function writeReviewBundles(
  entries = readStatusEntries(),
  outputDir = defaultReviewBundleDir,
  baseRef = readChangeScope().baseRef,
) {
  const bundles = groupStatusEntries(entries)

  rmSync(outputDir, { force: true, recursive: true })
  mkdirSync(outputDir, { recursive: true })
  writeFileSync(join(outputDir, 'README.md'), renderReviewBundleReadme(bundles))

  for (const bundle of bundles) {
    writeFileSync(
      join(outputDir, `${bundle.group.id}.files.txt`),
      renderFileList(bundle),
    )
    writeFileSync(
      join(outputDir, `${bundle.group.id}.patch`),
      renderGroupPatch(bundle, runGitDiff, baseRef),
    )
  }

  return { bundles, outputDir }
}

if (process.argv[1]?.endsWith('export-review-groups.ts')) {
  const outputDir =
    process.argv
      .find((arg) => arg.startsWith('--output-dir='))
      ?.split('=')[1] ?? defaultReviewBundleDir
  const { bundles } = writeReviewBundles(undefined, outputDir)
  const total = bundles.reduce((sum, bundle) => sum + bundle.entries.length, 0)

  console.log(
    `Wrote ${bundles.length} review group bundle(s) for ${total} changed path(s) to ${outputDir}`,
  )
}
