import { describe, expect, it } from 'vitest'

import {
  requiredQualityExitCriteria,
  verifyQualityExitFromTexts,
} from './verify-quality-exit'
import { changeGroups } from './verify-change-groups'

function completeTexts() {
  const scripts = {
    'review:groups': 'bun scripts/export-review-groups.ts',
    'test:coverage': 'vitest run --config vitest.config.ts --coverage',
    'verify:change-groups': 'bun scripts/verify-change-groups.ts',
    'verify:change-report':
      'bun scripts/verify-change-groups.ts --check-report',
    'verify:generated':
      'node packages/ship-fast-blocks/scripts/generate-react-export-sources.mjs --check',
    'verify:prepush': 'node scripts/git-hook-quality-gate.mjs pre-push',
    'verify:quality-exit': 'bun scripts/verify-quality-exit.ts',
    'verify:review-readiness': 'bun scripts/verify-review-readiness.ts',
  }

  return {
    assessment: [
      '# Code Quality Assessment Report',
      '## Repository Metrics Dashboard',
      '**Overall Rating: A (10.0/10).**',
    ].join('\n'),
    audit: [
      '# Quality Consolidation Audit',
      '## 11/10 Exit Criteria',
      ...requiredQualityExitCriteria,
    ].join('\n'),
    changeReport: changeGroups
      .map((group) => `## ${group.title} (1)\n\n- \`example.ts\``)
      .join('\n\n'),
    packageJson: JSON.stringify({ scripts }),
    reviewBundlesReadme: [
      '# Review Group Bundles',
      'Generated by `bun scripts/export-review-groups.ts`.',
      ...changeGroups.flatMap((group) => [
        `${group.id}.files.txt`,
        `${group.id}.patch`,
      ]),
    ].join('\n'),
  }
}

describe('quality exit verification', () => {
  it('accepts complete exit criteria, package wiring, manifest, and review bundle evidence', () => {
    expect(verifyQualityExitFromTexts(completeTexts())).toEqual({
      criteriaCount: requiredQualityExitCriteria.length,
      groupCount: changeGroups.length,
    })
  })

  it('fails when the audit drops an 11/10 exit criterion', () => {
    const texts = completeTexts()
    texts.audit = texts.audit.replace(requiredQualityExitCriteria[0], '')

    expect(() => verifyQualityExitFromTexts(texts)).toThrow(
      /missing 11\/10 exit criteria/,
    )
  })

  it('fails when package.json does not expose the final quality exit verifier', () => {
    const texts = completeTexts()
    texts.packageJson = JSON.stringify({ scripts: {} })

    expect(() => verifyQualityExitFromTexts(texts)).toThrow(
      /verify:quality-exit/,
    )
  })

  it('fails when review bundle artifacts are missing for a group', () => {
    const texts = completeTexts()
    texts.reviewBundlesReadme = texts.reviewBundlesReadme.replace(
      'openui-runtime-bundle-boundary.patch',
      '',
    )

    expect(() => verifyQualityExitFromTexts(texts)).toThrow(
      /openui-runtime-bundle-boundary\.patch/,
    )
  })

  it('fails when the assessment keeps stale quality evidence', () => {
    const texts = completeTexts()
    texts.assessment += '\nDate: 2026-06-17 (commit bfa35548)\n'

    expect(() => verifyQualityExitFromTexts(texts)).toThrow(
      /stale quality evidence: commit bfa35548/,
    )
  })
})
