import { existsSync, readFileSync } from 'node:fs'

import {
  groupStatusEntries,
  renderReviewBundleReadme,
} from './export-review-groups'
import {
  changeGroupReportPath,
  changeGroups,
  readChangeScope,
  readChangedPaths,
  renderChangeGroupReport,
  verifyChangeGroups,
} from './verify-change-groups'
import {
  reviewAuditPath,
  verifyReviewReadiness,
} from './verify-review-readiness'

export const qualityAssessmentPath =
  'specs/architecture/code_quality_assessment.md'
export const reviewBundlesReadmePath = '.quality-review-groups/README.md'

export const requiredQualityExitCriteria = [
  'The local branch/worktree scope is split into coherent, reviewable changesets.',
  'Full `verify:prepush` passes for the final assembled worktree.',
  'GitNexus `detect_changes` is understood at the group level, not dismissed as',
  '`bun run verify:change-groups` passes, proving every changed file is assigned',
  '`bun run verify:change-report` passes, proving the file-level review',
  '`bun run verify:review-readiness` passes, proving every review group has',
  '`bun run review:groups` has been run, producing ignored per-group file lists',
  'The assessment document reflects current metrics and no stale claims.',
  'Generated OpenUI/runtime artifacts have reproducible provenance.',
  'Source capsule files have reproducible origin classification.',
  'Coverage gates are enforced and meaningfully ratcheted, but not used as a',
  'Product-critical paths affected by the changes have real-path verification,',
]

const staleQualityEvidence = [
  'commit bfa35548',
  '.output/review-groups',
  '221 changed paths',
  '97 changed files',
  '468 changed symbols',
  '29 affected flows',
  '488 LOC',
  'below the preferred 500 LOC ceiling',
]

type QualityExitTexts = {
  audit: string
  assessment: string
  changeReport: string
  packageJson: string
  reviewBundlesReadme: string
}

function missingText(text: string, requiredText: string[]) {
  return requiredText.filter((needle) => !text.includes(needle))
}

function readRequiredFile(path: string) {
  if (!existsSync(path)) {
    throw new Error(`Missing required quality-exit file: ${path}`)
  }

  return readFileSync(path, 'utf8')
}

function withReportPath(paths: string[]) {
  return paths.includes(changeGroupReportPath)
    ? paths
    : [...paths, changeGroupReportPath].sort((a, b) => a.localeCompare(b))
}

export function verifyQualityExitFromTexts({
  audit,
  assessment,
  changeReport,
  packageJson,
  reviewBundlesReadme,
}: QualityExitTexts) {
  const failures: string[] = []
  const parsedPackage = JSON.parse(packageJson) as {
    scripts?: Record<string, string>
  }
  const scripts = parsedPackage.scripts ?? {}

  const missingCriteria = missingText(audit, requiredQualityExitCriteria)
  if (missingCriteria.length > 0) {
    failures.push(
      `${reviewAuditPath} is missing 11/10 exit criteria:\n- ${missingCriteria.join('\n- ')}`,
    )
  }

  if (scripts['verify:quality-exit'] !== 'bun scripts/verify-quality-exit.ts') {
    failures.push(
      'package.json must expose bun scripts/verify-quality-exit.ts as verify:quality-exit',
    )
  }

  for (const scriptName of [
    'verify:prepush',
    'verify:change-groups',
    'verify:change-report',
    'verify:review-readiness',
    'review:groups',
    'verify:generated',
    'test:coverage',
  ]) {
    if (!scripts[scriptName]) {
      failures.push(
        `package.json is missing required quality script: ${scriptName}`,
      )
    }
  }

  const coverageScript = scripts['test:coverage'] ?? ''
  if (coverageScript.includes('VITEST_COVERAGE')) {
    failures.push(
      'package.json test:coverage must run the coverage suite without VITEST_COVERAGE skips',
    )
  }

  const assessmentMissing = missingText(assessment, [
    '# Code Quality Assessment Report',
    'Overall Rating:',
    '## Repository Metrics Dashboard',
  ])
  if (assessmentMissing.length > 0) {
    failures.push(
      `${qualityAssessmentPath} is missing required assessment evidence:\n- ${assessmentMissing.join('\n- ')}`,
    )
  }

  for (const staleClaim of staleQualityEvidence) {
    for (const [label, text] of [
      [qualityAssessmentPath, assessment],
      [reviewAuditPath, audit],
    ] as const) {
      if (text.includes(staleClaim)) {
        failures.push(`${label} contains stale quality evidence: ${staleClaim}`)
      }
    }
  }

  const bundleMissing = missingText(reviewBundlesReadme, [
    '# Review Group Bundles',
    'Generated by `bun scripts/export-review-groups.ts`.',
  ])
  if (bundleMissing.length > 0) {
    failures.push(
      `${reviewBundlesReadmePath} is missing required review bundle evidence:\n- ${bundleMissing.join('\n- ')}`,
    )
  }

  for (const group of changeGroups) {
    const reportHeading = `## ${group.title} (`
    if (!changeReport.includes(reportHeading)) {
      failures.push(`${changeGroupReportPath} does not include ${group.title}`)
    }
  }

  const bundleIds = [
    ...reviewBundlesReadme.matchAll(/([a-z0-9-]+)\.files\.txt/g),
  ].map((match) => match[1])
  for (const bundleId of bundleIds) {
    const patch = `${bundleId}.patch`
    if (!reviewBundlesReadme.includes(patch)) {
      failures.push(`${reviewBundlesReadmePath} does not include ${patch}`)
    }
  }

  if (failures.length > 0) {
    throw new Error(
      `Quality exit verification failed:\n\n${failures.join('\n\n')}`,
    )
  }

  return {
    criteriaCount: requiredQualityExitCriteria.length,
    groupCount: changeGroups.length,
  }
}

export function verifyQualityExit() {
  const changedPaths = readChangedPaths()
  verifyChangeGroups(changedPaths)
  verifyReviewReadiness()

  const expectedChangeReport = renderChangeGroupReport(
    withReportPath(changedPaths),
  )
  const actualChangeReport = readRequiredFile(changeGroupReportPath)
  if (actualChangeReport !== expectedChangeReport) {
    throw new Error(
      `${changeGroupReportPath} is out of date. Run bun scripts/verify-change-groups.ts --write-report.`,
    )
  }

  const expectedReviewReadme = renderReviewBundleReadme(
    groupStatusEntries(readChangeScope().entries),
  )
  const actualReviewReadme = readRequiredFile(reviewBundlesReadmePath)
  if (actualReviewReadme !== expectedReviewReadme) {
    throw new Error(
      `${reviewBundlesReadmePath} is out of date. Run bun scripts/export-review-groups.ts.`,
    )
  }

  const assessment = readRequiredFile(qualityAssessmentPath)
  const audit = readRequiredFile(reviewAuditPath)

  if (!assessment.includes('Date: 2026-06-17 (local branch snapshot)')) {
    throw new Error(
      `${qualityAssessmentPath} does not identify the current local branch snapshot.`,
    )
  }

  return verifyQualityExitFromTexts({
    assessment,
    audit,
    changeReport: actualChangeReport,
    packageJson: readRequiredFile('package.json'),
    reviewBundlesReadme: actualReviewReadme,
  })
}

if (process.argv[1]?.endsWith('verify-quality-exit.ts')) {
  const summary = verifyQualityExit()
  console.log(
    `Quality exit evidence is wired for ${summary.groupCount} review group(s) and ${summary.criteriaCount} exit criteria.`,
  )
}
