import { describe, expect, it } from 'vitest'

import {
  classifyChangedPaths,
  parseGitNameStatusEntries,
  parseGitStatusPorcelainEntries,
  parseGitStatusPorcelain,
  renderChangeGroupReport,
  verifyChangeGroups,
} from './verify-change-groups'

describe('change group verification', () => {
  it('parses porcelain status output including untracked and renamed files', () => {
    const porcelain = [
      ' M package.json',
      '?? convex/lib/session_access_helpers.ts',
      'R  old/path.ts -> src/features/dashboard/components/Dashboard.tsx',
    ].join('\n')

    expect(parseGitStatusPorcelain(porcelain)).toEqual([
      'convex/lib/session_access_helpers.ts',
      'package.json',
      'src/features/dashboard/components/Dashboard.tsx',
    ])
    expect(parseGitStatusPorcelainEntries(porcelain)).toEqual([
      { path: 'convex/lib/session_access_helpers.ts', status: '??' },
      { path: 'package.json', status: ' M' },
      {
        path: 'src/features/dashboard/components/Dashboard.tsx',
        status: 'R ',
      },
    ])
  })

  it('parses git name-status output from committed branch diffs', () => {
    const nameStatus = [
      'M\tpackage.json',
      'A\tconvex/lib/session_access_helpers.ts',
      'R100\told/path.ts\tsrc/features/dashboard/components/Dashboard.tsx',
    ].join('\n')

    expect(parseGitNameStatusEntries(nameStatus)).toEqual([
      { path: 'convex/lib/session_access_helpers.ts', status: 'A' },
      { path: 'package.json', status: 'M' },
      {
        path: 'src/features/dashboard/components/Dashboard.tsx',
        status: 'R100',
      },
    ])
  })

  it('classifies representative consolidation files into review groups', () => {
    const { assignments, unclassified } = classifyChangedPaths([
      'convex/sessions.ts',
      'packages/ship-fast-blocks/src/runtime-library.ts',
      'packages/ship-fast-engine/src/spec/defaults.test.js',
      'scripts/git-hook-quality-gate.mjs',
      'src/features/dashboard/components/Dashboard.tsx',
      'src/routes/api/medusa-store.cart.ts',
      'specs/architecture/quality_consolidation_audit.md',
    ])

    expect(unclassified).toEqual([])
    expect(assignments.map((assignment) => assignment.group.id)).toEqual([
      'convex-session-decomposition',
      'openui-runtime-bundle-boundary',
      'engine-regression-coverage',
      'quality-gates-local-enforcement',
      'frontend-workflow-preview',
      'commerce-external-integration',
      'quality-documentation',
    ])
  })

  it('fails when a changed path is outside the documented review groups', () => {
    expect(() => verifyChangeGroups(['scratch/local-output.txt'])).toThrow(
      /Unclassified changed files/,
    )
  })

  it('renders a deterministic review manifest grouped by consolidation area', () => {
    expect(
      renderChangeGroupReport([
        'convex/sessions.ts',
        'scripts/verify-change-groups.ts',
        'specs/architecture/quality_change_groups.md',
      ]),
    ).toBe(
      [
        '# Quality Change Groups',
        '',
        'Generated by `bun scripts/verify-change-groups.ts --write-report`.',
        'Do not edit this file by hand; update `scripts/verify-change-groups.ts` or the changed files, then regenerate it.',
        '',
        'Total changed paths: 3',
        '',
        '## Convex session decomposition (1)',
        '',
        '- `convex/sessions.ts`',
        '',
        '## Quality gates and local enforcement (1)',
        '',
        '- `scripts/verify-change-groups.ts`',
        '',
        '## Quality documentation and assessment (1)',
        '',
        '- `specs/architecture/quality_change_groups.md`',
        '',
      ].join('\n'),
    )
  })
})
