export const INDIAN_SAMPLE_PROMPTS = [
  'An award-level editorial landing page for a premium Indian D2C brand with split hero, bento feature grid, glassmorphism cards, Fraunces or Syne display typography, aurora gradient bands, and subtle CSS motion on scroll.',
  'A cinematic fintech landing page for Indian founders with asymmetric layout, oversized numerals in the background, gradient mesh behind the hero, ring-glow CTAs, and monthly versus yearly pricing toggle with animated counters.',
  'A luxury hospitality landing page for a boutique Indian hotel chain with full-bleed atmospheric sections, pull-quote editorial blocks, testimonial carousel, and depth through layered blur panels — not a generic template.',
  'A Bharatanatyam academy landing page in mixed English–Tamil tone with guru profiles, beginner to arangetram tracks, rehearsal calendar, and fee structure for Chennai and online students.',
  'A Kathak dance school website with gharana lineage story, tabla and tatkar-focused batches, exam and certification pathway, and winter intensive workshop booking for North Indian cities.',
  'An Odissi dance foundation landing page highlighting temple sculpture inspiration, live orchestra collaborations, costume and jewellery notes, and residency applications for international learners.',
  'A Kuchipudi ensemble and summer intensive landing page with male and female repertoire highlights, story-based items, guest choreographers, and tiered passes for Hyderabad and Bengaluru.',
  'A Kathakali repertory company landing page with evening performance schedule, make-up and costume explainers, Kerala tourism tie-ups, and corporate and school show inquiry forms.',
  'A Mohiniyattam academy landing page with lasya-focused pedagogy, percussion ensemble details, Kerala festival calendar, and scholarship audition slots for young dancers.',
  'A Manipuri classical dance institution landing page with Ras Lila context, indigenous costume care, Imphal campus and outreach tours, and donor and CSR partnership blurbs.',
  'A Sattriya dance and neo-Vaishnavite culture centre landing page with monastery heritage framing, youth and adult batches, Assamese–English copy options, and grant and residency FAQs.',
  'A multi-style Indian classical dance festival landing page with Bharatanatyam Kathak Odissi showcase nights, masterclass tickets, volunteer signup, and sponsor deck download.',
  'A Navratri Garba and Dandiya event organiser landing page with city-wise venues, live dhol and DJ packages, group booking tiers, and safety and crowd management assurances.',
  'A Bhangra academy and college competition crew landing page with Punjab folk roots story, fitness-forward training tracks, costume rental add-ons, and corporate flash-mob packages.',
  'A Lavani and Maharashtrian folk performance collective landing page with rural outreach shows, urban theatre tie-ins, costume authenticity notes, and booking for weddings and corporate days.',
  'A Bihu and Assamese folk culture festival landing page with traditional dance and music slots, local food partner highlights, tourist itinerary hooks, and volunteer and vendor applications.',
  'A national handicrafts and handloom marketplace landing page with GI-tagged clusters, artisan stories, khadi and natural dye filters, and bulk order and export documentation help.',
  'A Madhubani and Mithila art gallery landing page with artist residency programmes, certificate courses, corporate gifting tiers, and international shipping and customs guidance.',
  'A Warli and tribal art tourism cooperative landing page with village homestay loops, painting workshop weekends, fair-trade pricing transparency, and guide and translator add-ons.',
  'A Carnatic music sabha season landing page with monthly kutcheri schedule, season passes, livestream add-on, parking and accessibility notes, and donor and patron circles.',
  'A Hindustani classical vocal and instrumental gurukul landing page with khayal and dhrupad tracks, tabla and harmonium faculty, examination pathway, and online riyaaz cohorts.',
  'A Jaipur Literature Festival–style literary conference landing page with author line-up grid, regional language tracks, student day passes, and sponsor and media kit downloads.',
  'A heritage walking tours operator landing page for Old Delhi Agra and Jaipur circuits with licensed guides, monument combo tickets, wheelchair-friendly route flags, and group charter pricing.',
  'A classical yoga and Natya Shastra–informed movement retreat landing page with abhinaya and rhythm modules, Ayurveda add-ons, ashram stay tiers, and silent-day policy copy.',
  'A trustworthy mixed Hindi-English landing page for a chartered accountant practice offering GST return filing, income tax, and ROC compliance with fees and appointment booking.',
  'A crisp company registration and startup India landing page for CS-led incorporation, MSME registration, and trademark filing with clear packages and timelines.',
  'A professional legal services website for contracts, IP filings, and litigation intake with lawyer profiles, practice areas, and a secure consultation request form.',
  'A B2B HR and payroll compliance landing page for Indian SMBs covering PF, ESI, PT, and payslip automation with pricing tiers and onboarding checklist.',
  'A manufacturing supplier directory style landing page for industrial components with RFQ flow, certifications, and tier-2 city logistics reassurance.',
  'An import-export and customs brokerage landing page with service lanes, documentation checklist, and shipment tracking CTA for Indian exporters.',
  'A facility management and security services landing page with AMC plans, guard deployment regions, and SLA-backed response times.',
  'A premium wedding and corporate event planner landing page with portfolio galleries, vendor coordination packages, and city-wise availability.',
  'A RERA-forward real estate brokerage landing page with project listings, virtual tours, and EMI calculator for Indian metro and tier-2 buyers.',
  'A co-living and PG operator landing page with room types, meal plans, house rules, and UPI-ready rent payment positioning.',
  'An interior design and modular kitchen studio landing page with 3D mood boards, material palettes, and city site-visit booking.',
  'A neighbourhood kirana going online landing page with daily essentials, slot delivery, and UPI QR trust cues for Bharat audiences.',
  'A regional FMCG snacks and spices brand landing page with festive bundles, nutrition callouts, and distributor inquiry for tier-2 retail.',
  'An ethnic wear and bridal boutique landing page with lookbook, made-to-measure appointments, and festival shipping timelines.',
  'A hallmarked jewellery showroom landing page with gold rate ticker, exchange policy, and store locator across Indian cities.',
  'A multi-brand electronics retail and authorised service landing page with warranty lookup, spare parts, and pickup repair slots.',
  'An EV dealership and charging solutions landing page with test-ride booking, subsidy FAQs, and service packages for Indian buyers.',
  'A fine-dine and family restaurant landing page with chef story, regional menu highlights, table reservation, and catering upsell.',
  'A cloud kitchen and delivery brand landing page with live order areas, combo meals, hygiene badges, and partner rider recruitment.',
  'A wedding and banquet catering landing page with per-plate tiers, live counters, tasting session booking, and city coverage map.',
  'A mithai and bakery chain landing page with sugar-free options, corporate gifting, and same-day delivery corridors.',
  'A specialty tea and filter coffee brand landing page with origin stories, subscription tins, and café franchise inquiry.',
  'A boutique hotel and homestay landing page with room stories, local experiences, seasonal tariffs, and direct booking incentives.',
  'A domestic pilgrimage and long-weekend travel landing page with curated itineraries, reviews, and fast flexible booking.',
  'A regional bus and intercity cab operator landing page with routes, live seat maps, safety checklist, and agent login hints.',
  'An FPO and farmer collective landing page with crop plans, mandi connect, transparent pricing charts, and member onboarding.',
  'An agri input dealer landing page with crop-wise catalogues, soil testing partners, and last-mile delivery to villages.',
  'A dairy and milk cooperative landing page with cold chain assurance, subscription milk plans, and quality lab highlights.',
  'A farm equipment rental landing page with tractor hourly rates, attachment catalogue, and operator safety training notes.',
  'An organic and natural farmer brand landing page with traceability QR story, certification badges, and metro delivery slots.',
  'A JEE NEET and state PSC coaching landing page with faculty panel, batch schedules, scholarship test, and parent dashboard teaser.',
  'A regional language edtech landing page with micro-courses, mobile-first lessons, and affordable annual plans for Bharat students.',
  'A vocational ITI and NSDC-aligned skilling landing page with placement partners, lab photos, and employer hiring day calendar.',
  'A study abroad and visa consulting landing page with university shortlists, SOP review, and loan partner pathways for Indian families.',
  'A multi-speciality hospital landing page with departments, insurance tie-ups, OT availability, and emergency contact strip.',
  'A diagnostics lab chain landing page with home collection slots, NABL highlights, and report download UX for patients.',
  'An ethical pharma distributor landing page with cold chain compliance, stockist locator, and doctor education webinar invites.',
  'An Ayurveda and integrative wellness clinic landing page with panchakarma packages, doctor credentials, and seasonal detox plans.',
  'A premium fitness studio landing page with class packs, trainer bios, body assessment booking, and nutrition add-ons.',
  'An NBFC gold loan and MSME lending landing page with transparent APR, branch locator, and minimal documentation promise.',
  'A health and term insurance comparison landing page with IRDAI disclaimers, premium illustrations, and claim assistance highlights.',
  'A mutual fund distributor and RIA landing page with goal calculators, risk questionnaire, and SIP mandate education for Indians.',
  'A stock broking and research landing page with margin FAQ, platform screenshots, and referral rewards tuned for retail traders.',
  'A UPI-first fintech landing page for bill pay, rewards, and credit-line waitlist with bank-grade security messaging.',
  'An NGO and CSR programme landing page with impact metrics, volunteer signup, donation transparency, and 80G note placeholders.',
  'A public health awareness microsite landing page with multilingual toggles, symptom checker caution, and helpline prominence.',
  'A regional digital news publication landing page with editor picks, newsletter signup, and membership wall for long-form.',
  'An indie podcast and creator network landing page with show tiles, sponsor kits, and RSS subscription guidance.',
  'A regional language book publisher landing page with author submissions, distributor map, and festival launch calendar.',
  'An independent film production landing page with slate teaser, casting note, festival laurels, and investor deck request.',
  'An offshore-ready IT services studio landing page with case studies, stack expertise, and timezone overlap chart for US EU clients.',
  'A GST payroll and inventory SaaS for Indian SMBs landing page with CA partner programme, demo video, and pricing in rupees.',
  'A cybersecurity and GRC consulting landing page with audit offerings, breach response retainer, and compliance checklist downloads.',
  'A solar EPC and rooftop landing page with subsidy steps, generation calculator, and O&M warranty table for homes and SMEs.',
  'A logistics and 3PL landing page with pincode SLA map, freight calculator, and COD reconciliation highlights for ecommerce brands.',
  'A civil construction and contracting landing page with project portfolio, RERA mention, safety record, and tender inquiry form.',
  'A community-focused matrimony landing page with verification layers, family-friendly copy, and privacy controls emphasis.',
  'A temple trust and donation landing page with darshan timings, seva booking, 80G transparency, and festival crowd management info.',
  'A sports academy landing page with coaching levels, turf booking, nutrition partners, and parent progress portal teaser.',
  'A parenting and kids activity centre landing page with age bands, weekend workshops, and trial class booking flow.',
  'A tier-3 city coaching centre landing page with hostel tie-ups, daily test series, and scholarship stories in Hinglish tone.',
  'A seafood and poultry integrated brand landing page with cold chain badges, cut options, and metro morning delivery promise.',
  'A warehouse and cold storage operator landing page with pallet pricing, CCTV assurance, and FMCH client logos.',
  'A college placement cell microsite landing page with recruiter timeline, student achievement wall, and training partner list.',
  'A boutique law firm for startups landing page with flat-fee bundles, cap table clinic, and founder office hours booking.',
  'A mobile wallet and recharge super-app landing page with rewards, bill categories, and KYC upgrade journey for India users.',
]
