/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionSessionIdRouteImport } from './routes/session.$sessionId'
import { Route as PreviewLookupRouteImport } from './routes/preview.$lookup'
import { Route as GenerateSessionIdRouteImport } from './routes/generate.$sessionId'
import { Route as ApiStudioEmbedReadyRouteImport } from './routes/api/studio-embed-ready'
import { Route as ApiSessionsRouteImport } from './routes/api/sessions'
import { Route as ApiRewriteRouteImport } from './routes/api/rewrite'
import { Route as ApiPromptSuggestionsRouteImport } from './routes/api/prompt-suggestions'
import { Route as ExportSessionIdTargetRouteImport } from './routes/export.$sessionId.$target'
import { Route as ApiSessionsSessionIdRouteImport } from './routes/api/sessions.$sessionId'
import { Route as ApiSessionsSessionIdStreamRouteImport } from './routes/api/sessions.$sessionId.stream'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionSessionIdRoute = SessionSessionIdRouteImport.update({
  id: '/session/$sessionId',
  path: '/session/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewLookupRoute = PreviewLookupRouteImport.update({
  id: '/preview/$lookup',
  path: '/preview/$lookup',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateSessionIdRoute = GenerateSessionIdRouteImport.update({
  id: '/generate/$sessionId',
  path: '/generate/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStudioEmbedReadyRoute = ApiStudioEmbedReadyRouteImport.update({
  id: '/api/studio-embed-ready',
  path: '/api/studio-embed-ready',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionsRoute = ApiSessionsRouteImport.update({
  id: '/api/sessions',
  path: '/api/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRewriteRoute = ApiRewriteRouteImport.update({
  id: '/api/rewrite',
  path: '/api/rewrite',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPromptSuggestionsRoute = ApiPromptSuggestionsRouteImport.update({
  id: '/api/prompt-suggestions',
  path: '/api/prompt-suggestions',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportSessionIdTargetRoute = ExportSessionIdTargetRouteImport.update({
  id: '/export/$sessionId/$target',
  path: '/export/$sessionId/$target',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionsSessionIdRoute = ApiSessionsSessionIdRouteImport.update({
  id: '/$sessionId',
  path: '/$sessionId',
  getParentRoute: () => ApiSessionsRoute,
} as any)
const ApiSessionsSessionIdStreamRoute =
  ApiSessionsSessionIdStreamRouteImport.update({
    id: '/stream',
    path: '/stream',
    getParentRoute: () => ApiSessionsSessionIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gallery': typeof GalleryRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/studio': typeof StudioRoute
  '/terms': typeof TermsRoute
  '/api/prompt-suggestions': typeof ApiPromptSuggestionsRoute
  '/api/rewrite': typeof ApiRewriteRoute
  '/api/sessions': typeof ApiSessionsRouteWithChildren
  '/api/studio-embed-ready': typeof ApiStudioEmbedReadyRoute
  '/generate/$sessionId': typeof GenerateSessionIdRoute
  '/preview/$lookup': typeof PreviewLookupRoute
  '/session/$sessionId': typeof SessionSessionIdRoute
  '/api/sessions/$sessionId': typeof ApiSessionsSessionIdRouteWithChildren
  '/export/$sessionId/$target': typeof ExportSessionIdTargetRoute
  '/api/sessions/$sessionId/stream': typeof ApiSessionsSessionIdStreamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gallery': typeof GalleryRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/studio': typeof StudioRoute
  '/terms': typeof TermsRoute
  '/api/prompt-suggestions': typeof ApiPromptSuggestionsRoute
  '/api/rewrite': typeof ApiRewriteRoute
  '/api/sessions': typeof ApiSessionsRouteWithChildren
  '/api/studio-embed-ready': typeof ApiStudioEmbedReadyRoute
  '/generate/$sessionId': typeof GenerateSessionIdRoute
  '/preview/$lookup': typeof PreviewLookupRoute
  '/session/$sessionId': typeof SessionSessionIdRoute
  '/api/sessions/$sessionId': typeof ApiSessionsSessionIdRouteWithChildren
  '/export/$sessionId/$target': typeof ExportSessionIdTargetRoute
  '/api/sessions/$sessionId/stream': typeof ApiSessionsSessionIdStreamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gallery': typeof GalleryRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/studio': typeof StudioRoute
  '/terms': typeof TermsRoute
  '/api/prompt-suggestions': typeof ApiPromptSuggestionsRoute
  '/api/rewrite': typeof ApiRewriteRoute
  '/api/sessions': typeof ApiSessionsRouteWithChildren
  '/api/studio-embed-ready': typeof ApiStudioEmbedReadyRoute
  '/generate/$sessionId': typeof GenerateSessionIdRoute
  '/preview/$lookup': typeof PreviewLookupRoute
  '/session/$sessionId': typeof SessionSessionIdRoute
  '/api/sessions/$sessionId': typeof ApiSessionsSessionIdRouteWithChildren
  '/export/$sessionId/$target': typeof ExportSessionIdTargetRoute
  '/api/sessions/$sessionId/stream': typeof ApiSessionsSessionIdStreamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/gallery'
    | '/pricing'
    | '/privacy'
    | '/studio'
    | '/terms'
    | '/api/prompt-suggestions'
    | '/api/rewrite'
    | '/api/sessions'
    | '/api/studio-embed-ready'
    | '/generate/$sessionId'
    | '/preview/$lookup'
    | '/session/$sessionId'
    | '/api/sessions/$sessionId'
    | '/export/$sessionId/$target'
    | '/api/sessions/$sessionId/stream'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/gallery'
    | '/pricing'
    | '/privacy'
    | '/studio'
    | '/terms'
    | '/api/prompt-suggestions'
    | '/api/rewrite'
    | '/api/sessions'
    | '/api/studio-embed-ready'
    | '/generate/$sessionId'
    | '/preview/$lookup'
    | '/session/$sessionId'
    | '/api/sessions/$sessionId'
    | '/export/$sessionId/$target'
    | '/api/sessions/$sessionId/stream'
  id:
    | '__root__'
    | '/'
    | '/gallery'
    | '/pricing'
    | '/privacy'
    | '/studio'
    | '/terms'
    | '/api/prompt-suggestions'
    | '/api/rewrite'
    | '/api/sessions'
    | '/api/studio-embed-ready'
    | '/generate/$sessionId'
    | '/preview/$lookup'
    | '/session/$sessionId'
    | '/api/sessions/$sessionId'
    | '/export/$sessionId/$target'
    | '/api/sessions/$sessionId/stream'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GalleryRoute: typeof GalleryRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  StudioRoute: typeof StudioRoute
  TermsRoute: typeof TermsRoute
  ApiPromptSuggestionsRoute: typeof ApiPromptSuggestionsRoute
  ApiRewriteRoute: typeof ApiRewriteRoute
  ApiSessionsRoute: typeof ApiSessionsRouteWithChildren
  ApiStudioEmbedReadyRoute: typeof ApiStudioEmbedReadyRoute
  GenerateSessionIdRoute: typeof GenerateSessionIdRoute
  PreviewLookupRoute: typeof PreviewLookupRoute
  SessionSessionIdRoute: typeof SessionSessionIdRoute
  ExportSessionIdTargetRoute: typeof ExportSessionIdTargetRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$sessionId': {
      id: '/session/$sessionId'
      path: '/session/$sessionId'
      fullPath: '/session/$sessionId'
      preLoaderRoute: typeof SessionSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/$lookup': {
      id: '/preview/$lookup'
      path: '/preview/$lookup'
      fullPath: '/preview/$lookup'
      preLoaderRoute: typeof PreviewLookupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate/$sessionId': {
      id: '/generate/$sessionId'
      path: '/generate/$sessionId'
      fullPath: '/generate/$sessionId'
      preLoaderRoute: typeof GenerateSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/studio-embed-ready': {
      id: '/api/studio-embed-ready'
      path: '/api/studio-embed-ready'
      fullPath: '/api/studio-embed-ready'
      preLoaderRoute: typeof ApiStudioEmbedReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sessions': {
      id: '/api/sessions'
      path: '/api/sessions'
      fullPath: '/api/sessions'
      preLoaderRoute: typeof ApiSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rewrite': {
      id: '/api/rewrite'
      path: '/api/rewrite'
      fullPath: '/api/rewrite'
      preLoaderRoute: typeof ApiRewriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/prompt-suggestions': {
      id: '/api/prompt-suggestions'
      path: '/api/prompt-suggestions'
      fullPath: '/api/prompt-suggestions'
      preLoaderRoute: typeof ApiPromptSuggestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export/$sessionId/$target': {
      id: '/export/$sessionId/$target'
      path: '/export/$sessionId/$target'
      fullPath: '/export/$sessionId/$target'
      preLoaderRoute: typeof ExportSessionIdTargetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sessions/$sessionId': {
      id: '/api/sessions/$sessionId'
      path: '/$sessionId'
      fullPath: '/api/sessions/$sessionId'
      preLoaderRoute: typeof ApiSessionsSessionIdRouteImport
      parentRoute: typeof ApiSessionsRoute
    }
    '/api/sessions/$sessionId/stream': {
      id: '/api/sessions/$sessionId/stream'
      path: '/stream'
      fullPath: '/api/sessions/$sessionId/stream'
      preLoaderRoute: typeof ApiSessionsSessionIdStreamRouteImport
      parentRoute: typeof ApiSessionsSessionIdRoute
    }
  }
}

interface ApiSessionsSessionIdRouteChildren {
  ApiSessionsSessionIdStreamRoute: typeof ApiSessionsSessionIdStreamRoute
}

const ApiSessionsSessionIdRouteChildren: ApiSessionsSessionIdRouteChildren = {
  ApiSessionsSessionIdStreamRoute: ApiSessionsSessionIdStreamRoute,
}

const ApiSessionsSessionIdRouteWithChildren =
  ApiSessionsSessionIdRoute._addFileChildren(ApiSessionsSessionIdRouteChildren)

interface ApiSessionsRouteChildren {
  ApiSessionsSessionIdRoute: typeof ApiSessionsSessionIdRouteWithChildren
}

const ApiSessionsRouteChildren: ApiSessionsRouteChildren = {
  ApiSessionsSessionIdRoute: ApiSessionsSessionIdRouteWithChildren,
}

const ApiSessionsRouteWithChildren = ApiSessionsRoute._addFileChildren(
  ApiSessionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GalleryRoute: GalleryRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  StudioRoute: StudioRoute,
  TermsRoute: TermsRoute,
  ApiPromptSuggestionsRoute: ApiPromptSuggestionsRoute,
  ApiRewriteRoute: ApiRewriteRoute,
  ApiSessionsRoute: ApiSessionsRouteWithChildren,
  ApiStudioEmbedReadyRoute: ApiStudioEmbedReadyRoute,
  GenerateSessionIdRoute: GenerateSessionIdRoute,
  PreviewLookupRoute: PreviewLookupRoute,
  SessionSessionIdRoute: SessionSessionIdRoute,
  ExportSessionIdTargetRoute: ExportSessionIdTargetRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
