// v3 Convex code generation — transforms a LakebedDefinition into actual
// Convex schema + query/mutation function source code. This is the bridge
// that makes v3 fully fullstack: the lakebed is no longer just metadata,
// it generates real, deployable Convex backend code.
import type {
  LakebedDefinition,
  LakebedTable,
  LakebedField,
  LakebedQuery,
  LakebedMutation,
} from './types.ts'

/** Generate the Convex schema.ts file from lakebed tables. */
export function generateConvexSchema(lakebed: LakebedDefinition): string {
  if (lakebed.tables.length === 0) return ''

  const tableDefs = lakebed.tables.map((table) => {
    const fieldLines = Object.entries(table.fields).map(([name, field]) => {
      const typeFn = field.type === 'number' ? 'v.number()' : 'v.string()'
      const defaultPart =
        field.default !== '' && field.default !== 0
          ? `.default(${JSON.stringify(field.default)})`
          : ''
      return `    ${name}: ${typeFn}${defaultPart},`
    })
    // Every table gets updatedAt for orderBy('updatedAt','desc')
    if (!fieldLines.some((l) => l.includes('updatedAt'))) {
      fieldLines.push('    updatedAt: v.number(),')
    }
    return `  ${table.name}: defineTable({\n${fieldLines.join('\n')}\n  }),`
  })

  return `import { defineSchema, defineTable } from 'convex/server'
import { v } from 'convex/values'

export default defineSchema({
${tableDefs.join('\n')}
})
`
}

/** Generate a single Convex query function source. */
function generateQuerySource(query: LakebedQuery): string {
  return `export const ${query.name} = query({
  handler: async (ctx) => {
    return await ctx.db.query('${query.table}').order('desc').collect()
  },
})
`
}

/** Generate a single Convex mutation function source. */
function generateMutationSource(mutation: LakebedMutation): string {
  // Parse the body to determine args — the macro body format is:
  // ctx.db.{table}.upsert({{firstField}: args.{firstField}}, args)
  // or ctx.db.{table}.insert(args)
  // or ctx.db.{table}.patch({id: args.id}, args)
  const argsMatch = mutation.body.match(/args\.(\w+)/g)
  const argNames = argsMatch
    ? [...new Set(argsMatch.map((m) => m.replace('args.', '')))]
    : []

  const argsObj = argNames.map((name) => `    ${name}: v.string(),`).join('\n')

  // Convert the macro body to a real Convex handler body
  let handlerBody = mutation.body
  // Replace ctx.db.{table}.upsert with ctx.db.query + patch/insert pattern
  if (handlerBody.includes('upsert')) {
    const fieldMatch = handlerBody.match(/\{(\w+):\s*args\.(\w+)\}/)
    const keyField = fieldMatch?.[1] ?? 'id'
    handlerBody = `    const existing = await ctx.db
      .query('${mutation.table}')
      .filter((q) => q.eq(q.field('${keyField}'), args.${keyField}))
      .first()
    if (existing) {
      return await ctx.db.patch(existing._id, args)
    }
    return await ctx.db.insert('${mutation.table}', args)`
  } else if (handlerBody.includes('insert')) {
    handlerBody = `    return await ctx.db.insert('${mutation.table}', args)`
  } else if (handlerBody.includes('patch')) {
    handlerBody = `    const doc = await ctx.db
      .query('${mutation.table}')
      .filter((q) => q.eq(q.field('id'), args.id))
      .first()
    if (!doc) throw new Error('Not found')
    return await ctx.db.patch(doc._id, args)`
  } else {
    // Generic fallback — just run the body as-is (it's already valid-ish)
    handlerBody = `    ${handlerBody}`
  }

  return `export const ${mutation.name} = mutation({
  args: {
${argsObj}
  },
  handler: async (ctx, args) => {
${handlerBody}
  },
})
`
}

/** Generate all Convex function files from the lakebed. Returns a map of
 *  file path → source code, ready to be written to the convex/ directory. */
export function generateConvexFunctions(
  lakebed: LakebedDefinition,
): Record<string, string> {
  const files: Record<string, string> = {}

  // Group queries and mutations into files by table name
  const byTable: Record<
    string,
    { queries: LakebedQuery[]; mutations: LakebedMutation[] }
  > = {}

  for (const query of lakebed.queries) {
    const key = query.table
    if (!byTable[key]) byTable[key] = { queries: [], mutations: [] }
    byTable[key].queries.push(query)
  }
  for (const mutation of lakebed.mutations) {
    const key = mutation.table
    if (!byTable[key]) byTable[key] = { queries: [], mutations: [] }
    byTable[key].mutations.push(mutation)
  }

  for (const [table, group] of Object.entries(byTable)) {
    const parts: string[] = [
      `// Auto-generated by ship-fast v3 engine — ${table} table operations.`,
      `import { query, mutation } from './_generated/server'`,
      `import { v } from 'convex/values'`,
      '',
    ]
    for (const q of group.queries) {
      parts.push(generateQuerySource(q))
    }
    for (const m of group.mutations) {
      parts.push(generateMutationSource(m))
    }
    files[`convex/${table}.ts`] = parts.join('\n')
  }

  return files
}

/** Generate a seed data file from the lakebed tables that have seedFromProps.
 *  This populates the tables with initial data from the LLM-authored content. */
export function generateSeedScript(
  lakebed: LakebedDefinition,
  seedData: Record<string, unknown[]>,
): string {
  const seedFns = Object.entries(seedData)
    .filter(([_, items]) => Array.isArray(items) && items.length > 0)
    .map(([table, items]) => {
      const itemsStr = JSON.stringify(items, null, 2)
      return `export const seed${table.charAt(0).toUpperCase() + table.slice(1)} = ${itemsStr}`
    })

  if (seedFns.length === 0) return ''

  return `// Auto-generated seed data from ship-fast v3 engine.
// Run with: npx convex run seed/seedData.ts:seedAll

${seedFns.join('\n\n')}

export const seedAll = mutation({
  handler: async (ctx) => {
${Object.keys(seedData)
  .filter((t) => Array.isArray(seedData[t]) && seedData[t].length > 0)
  .map(
    (t) =>
      `    for (const item of seed${t.charAt(0).toUpperCase() + t.slice(1)}) {
      await ctx.db.insert('${t}', item)
    }`,
  )
  .join('\n')}
  },
})
`
}

/** Full Convex codegen — schema + functions + seed data.
 *  Returns a map of file path → source code for the entire Convex backend. */
export function generateConvexBackend(
  lakebed: LakebedDefinition,
  seedData?: Record<string, unknown[]>,
): Record<string, string> {
  const files: Record<string, string> = {}

  const schema = generateConvexSchema(lakebed)
  if (schema) files['convex/schema.ts'] = schema

  Object.assign(files, generateConvexFunctions(lakebed))

  if (seedData) {
    const seed = generateSeedScript(lakebed, seedData)
    if (seed) files['convex/seed/seedData.ts'] = seed
  }

  return files
}
