// v3 engine — generates a $lakebed client module from a LakebedDefinition.
// The generated module exposes typed query/mutation functions that Svelte
// components import for database access. Uses ConvexClient from convex/browser
// (non-React, works inside Svelte islands).

import type { LakebedDefinition } from './types.ts'

/** Generate a $lakebed client module from a LakebedDefinition.
 *  The module exports `queries` and `mutations` objects with typed methods.
 *  Each method wraps a ConvexClient query/mutation call. */
export function generateLakebedClient(lakebed: LakebedDefinition): string {
  const queryEntries = lakebed.queries.map((q) => {
    // Parse args from the query body (if any)
    const args = parseArgsFromBody(q.body)
    if (args.length > 0) {
      const argsObj = args.map((a) => `'${a}': ${a}`).join(', ')
      return `  ${q.name}: (${args.map((a) => a).join(', ')}) => client.query('${q.name}', { ${argsObj} }),`
    }
    return `  ${q.name}: () => client.query('${q.name}'),`
  })

  const mutationEntries = lakebed.mutations.map((m) => {
    const args = parseArgsFromBody(m.body)
    if (args.length > 0) {
      const argsObj = args.map((a) => `'${a}': ${a}`).join(', ')
      return `  ${m.name}: (${args.map((a) => a).join(', ')}) => client.mutation('${m.name}', { ${argsObj} }),`
    }
    return `  ${m.name}: () => client.mutation('${m.name}'),`
  })

  return `// Auto-generated $lakebed client module.
// Do not edit — regenerated by the V3 engine on each compilation.
// Provides typed access to Convex queries and mutations from Svelte components.
import { ConvexClient } from 'convex/browser'

const convexUrl = import.meta.env.VITE_CONVEX_URL || ''
const client = new ConvexClient(convexUrl)

export const queries = {
${queryEntries.join('\n')}
}

export const mutations = {
${mutationEntries.join('\n')}
}

export { client }
`
}

/** Parse argument names from a lakebed query/mutation body string.
 *  The body uses `args.fieldName` syntax; we extract the field names. */
function parseArgsFromBody(body: string): string[] {
  const args = new Set<string>()
  const regex = /args\.(\w+)/g
  let match: RegExpExecArray | null
  while ((match = regex.exec(body)) !== null) {
    args.add(match[1])
  }
  return Array.from(args)
}
