// Server-safe taxonomy for the GenUI orchestrator. NO React/JSX imports here —
// this module is consumed by orchestrator.ts on the server to drive deterministic,
// varied block selection and zero-broken-link navigation.

export type Category =
  | "marketing"
  | "saas"
  | "ecommerce"
  | "blog"
  | "portfolio"
  | "pricing"
  | "about"
  | "contact"
  | "agency"
  | "restaurant"
  | "event"
  | "dashboard"
  | "auth"
  | "game"

export type NavPageType =
  | "home"
  | "landing"
  | "list"
  | "index"
  | "detail"
  | "about"
  | "contact"
  | "pricing"
  | "gallery"
  | "team"
  | "features"
  | "menu"
  | "schedule"
  | "auth"
  | "dashboard"

export interface BlockMeta {
  category: Category
  navPageType: NavPageType
  tags: string[]
  // index/list pages set false (e.g. a blog index must NOT contain a hero)
  allowHero: boolean
}

// Keyed by the `defineComponent` name of each page block in registry/pages.
// These names are the contract between the orchestrator and the page blocks.
export const BLOCK_TAXONOMY: Record<string, BlockMeta> = {
  SaasKimiPage: {
    category: "saas",
    navPageType: "home",
    tags: [
      "saas",
      "software",
      "ai",
      "product",
      "app",
      "b2b",
      "platform",
      "scheduling",
      "automation",
      "productivity",
      "landing",
      "home",
      "pricing",
      "social-proof",
      "kimi",
    ],
    allowHero: true,
  },
  PortfolioKimiPage: {
    category: "portfolio",
    navPageType: "home",
    tags: [
      "portfolio",
      "3d-artist",
      "motion-designer",
      "art-director",
      "cgi",
      "vfx",
      "animator",
      "creative",
      "dark",
      "cinematic",
      "showcase",
      "work",
      "home",
      "kimi",
    ],
    allowHero: true,
  },
  PricingKimiPage: {
    category: "pricing",
    navPageType: "pricing",
    tags: [
      "pricing",
      "plans",
      "tiers",
      "subscription",
      "billing",
      "cloud",
      "storage",
      "saas",
      "toggle",
      "monthly-yearly",
      "comparison",
      "faq",
      "kimi",
      "no-hero",
    ],
    allowHero: false,
  },
  RestaurantKimiPage: {
    category: "restaurant",
    navPageType: "home",
    tags: [
      "restaurant",
      "ramen",
      "izakaya",
      "japanese",
      "food",
      "menu",
      "dining",
      "reservation",
      "dark",
      "image-led",
      "home",
      "landing",
      "kimi",
    ],
    allowHero: true,
  },
  MarketingKimiPage: {
    category: "marketing",
    navPageType: "home",
    tags: ["marketing", "landing", "saas", "product", "premium", "hero", "home", "kimi"],
    allowHero: true,
  },
  ShopKimiPage: {
    category: "ecommerce",
    navPageType: "list",
    tags: ["ecommerce", "shop", "store", "sneakers", "products", "retail", "catalog", "kimi"],
    allowHero: true,
  },
  BlogKimiPage: {
    category: "blog",
    navPageType: "index",
    tags: ["blog", "articles", "editorial", "magazine", "posts", "index", "no-hero", "kimi"],
    allowHero: false,
  },
  AgencyKimiPage: {
    category: "agency",
    navPageType: "home",
    tags: ["agency", "studio", "creative", "design", "portfolio", "work", "services", "home", "kimi"],
    allowHero: true,
  },
  MobileAppKimiPage: {
    category: "saas",
    navPageType: "home",
    tags: ["mobile","habit","tracking","phone","mockups","store","badges"],
    allowHero: true,
  },
  DevToolKimiPage: {
    category: "saas",
    navPageType: "home",
    tags: ["developer","tool","platform","code","samples","integration","logos"],
    allowHero: true,
  },
  AiProductKimiPage: {
    category: "saas",
    navPageType: "home",
    tags: ["product","generative","writing","assistant"],
    allowHero: true,
  },
  PhotographyKimiPage: {
    category: "portfolio",
    navPageType: "gallery",
    tags: ["photography","portfolio","full","bleed","masonry","gallery","services","contact"],
    allowHero: true,
  },
  NewsKimiPage: {
    category: "blog",
    navPageType: "index",
    tags: ["news","magazine","homepage","stories","category","trending","sidebar"],
    allowHero: false,
  },
  PodcastKimiPage: {
    category: "blog",
    navPageType: "home",
    tags: ["podcast","show","play","button","latest","episodes","list","subscribe"],
    allowHero: true,
  },
  LawFirmKimiPage: {
    category: "agency",
    navPageType: "home",
    tags: ["firm","authoritative","practice","areas","attorneys","consultation"],
    allowHero: true,
  },
  FintechKimiPage: {
    category: "saas",
    navPageType: "home",
    tags: ["fintech","digital","wallet","banking","card","visual","security","features"],
    allowHero: true,
  },
  CryptoKimiPage: {
    category: "saas",
    navPageType: "home",
    tags: ["crypto","platform","token","visual","live","stats","roadmap"],
    allowHero: true,
  },
  HealthcareKimiPage: {
    category: "marketing",
    navPageType: "home",
    tags: ["healthcare","clinic","services","doctors","testimonials","booking"],
    allowHero: true,
  },
  FitnessKimiPage: {
    category: "marketing",
    navPageType: "home",
    tags: ["fitness","studio","classes","schedule","membership","tiers","trainers"],
    allowHero: true,
  },
  OnlineCourseKimiPage: {
    category: "marketing",
    navPageType: "home",
    tags: ["online","course","popular","courses","instructors","signup"],
    allowHero: true,
  },
  RealEstateKimiPage: {
    category: "marketing",
    navPageType: "home",
    tags: ["estate","agency","property","search","listings","agents"],
    allowHero: true,
  },
  HotelResortKimiPage: {
    category: "marketing",
    navPageType: "home",
    tags: ["luxury","hotel","resort","rooms","amenities","gallery","booking"],
    allowHero: true,
  },
  NonprofitKimiPage: {
    category: "marketing",
    navPageType: "home",
    tags: ["nonprofit","charity","mission","impact","stats","programs","donate"],
    allowHero: true,
  },
  DocsKimiPage: {
    category: "saas",
    navPageType: "index",
    tags: ["developer","documentation","sidebar","search","getting","started","code","block"],
    allowHero: false,
  },
  AnalyticsKimiPage: {
    category: "dashboard",
    navPageType: "dashboard",
    tags: ["saas","analytics","dashboard","sidebar","charts","data","table"],
    allowHero: false,
  },
  DashboardKimiPage: {
    category: "dashboard",
    navPageType: "dashboard",
    tags: ["dashboard", "analytics", "admin", "orders", "metrics", "back-office"],
    allowHero: false,
  },
  CybersecurityKimiPage: {
    category: "saas",
    navPageType: "home",
    tags: ["cybersecurity","platform","trust","forward","threat","stats","enterprise","logos"],
    allowHero: true,
  },
  CloudInfraKimiPage: {
    category: "saas",
    navPageType: "home",
    tags: ["cloud","infrastructure","hosting","platform","pricing","usage"],
    allowHero: true,
  },
  NoCodeKimiPage: {
    category: "saas",
    navPageType: "home",
    tags: ["code","builder","drag","drop","visual","templates","gallery"],
    allowHero: true,
  },
  CrmKimiPage: {
    category: "saas",
    navPageType: "home",
    tags: ["sales","platform","pipeline","visual","integrations"],
    allowHero: true,
  },
  ProductDetailKimiPage: {
    category: "ecommerce",
    navPageType: "detail",
    tags: ["commerce","product","detail","image","gallery","size","color","selectors"],
    allowHero: false,
  },
  EcommerceKimiPage: {
    category: "ecommerce",
    navPageType: "home",
    tags: ["ecommerce", "shop", "store", "sneakers", "products", "retail", "catalog", "kimi"],
    allowHero: true,
  },
  EcommerceKimiPage2: {
    category: "ecommerce",
    navPageType: "home",
    tags: ["ecommerce", "shop", "store", "sneakers", "products", "retail", "catalog", "kimi"],
    allowHero: true,
  },
  FashionStoreKimiPage: {
    category: "ecommerce",
    navPageType: "home",
    tags: ["fashion","apparel","online","store","homepage","editorial","lookbook","driven"],
    allowHero: true,
  },
  ElectronicsStoreKimiPage: {
    category: "ecommerce",
    navPageType: "home",
    tags: ["electronics","gadgets","online","store","homepage","deals","product"],
    allowHero: true,
  },
  FurnitureStoreKimiPage: {
    category: "ecommerce",
    navPageType: "home",
    tags: ["furniture","home","decor","store","homepage","warm","minimal","room"],
    allowHero: true,
  },
  BeautyStoreKimiPage: {
    category: "ecommerce",
    navPageType: "home",
    tags: ["beauty","cosmetics","store","homepage","clean","pastel","bestsellers"],
    allowHero: true,
  },
  JewelryStoreKimiPage: {
    category: "ecommerce",
    navPageType: "home",
    tags: ["luxury","jewelry","store","homepage","elegant","dark","piece","collections"],
    allowHero: true,
  },
  MarketplaceKimiPage: {
    category: "ecommerce",
    navPageType: "list",
    tags: ["multi","vendor","marketplace","homepage","categories","featured","sellers","trending"],
    allowHero: true,
  },
  SubscriptionBoxKimiPage: {
    category: "ecommerce",
    navPageType: "home",
    tags: ["subscription","coffee","works","plan","tiers"],
    allowHero: true,
  },
  FoodDeliveryKimiPage: {
    category: "ecommerce",
    navPageType: "home",
    tags: ["food","delivery","restaurant","tiles","order"],
    allowHero: true,
  },
  PortfolioDevKimiPage: {
    category: "portfolio",
    navPageType: "home",
    tags: ["software","developer","portfolio","projects","skills","open","source","work"],
    allowHero: true,
  },
  ResumeCvKimiPage: {
    category: "portfolio",
    navPageType: "home",
    tags: ["personal","resume","experience","timeline","skills"],
    allowHero: true,
  },
  MusicArtistKimiPage: {
    category: "portfolio",
    navPageType: "home",
    tags: ["music","artist","band","latest","release","tour","dates"],
    allowHero: true,
  },
  FilmDirectorKimiPage: {
    category: "portfolio",
    navPageType: "home",
    tags: ["film","director","videographer","portfolio","cinematic","reel"],
    allowHero: true,
  },
  WriterAuthorKimiPage: {
    category: "portfolio",
    navPageType: "home",
    tags: ["author","book","about","reviews","links"],
    allowHero: true,
  },
  IllustratorKimiPage: {
    category: "portfolio",
    navPageType: "home",
    tags: ["illustrator","artist","portfolio","playful","colorful","work","gallery","shop"],
    allowHero: true,
  },
  BlogPostKimiPage: {
    category: "blog",
    navPageType: "detail",
    tags: ["readable","blog","article","title","author","cover","image","long"],
    allowHero: false,
  },
  NewsletterKimiPage: {
    category: "marketing",
    navPageType: "home",
    tags: ["substack","style","newsletter","subscribe","form","what","recent","issues"],
    allowHero: true,
  },
  VideoStreamingKimiPage: {
    category: "marketing",
    navPageType: "home",
    tags: ["video","streaming","service","featured","content","rows","plan"],
    allowHero: true,
  },
  KnowledgeBaseKimiPage: {
    category: "saas",
    navPageType: "home",
    tags: ["help","center","knowledge","base","home","search","popular","topics"],
    allowHero: true,
  },
  MarketingAgencyKimiPage: {
    category: "agency",
    navPageType: "home",
    tags: ["marketing","growth","agency","results","stats","services","case","studies"],
    allowHero: true,
  },
  ConsultingKimiPage: {
    category: "agency",
    navPageType: "home",
    tags: ["management","consulting","firm","corporate","trustworthy","services","insights"],
    allowHero: true,
  },
  AccountingFirmKimiPage: {
    category: "agency",
    navPageType: "home",
    tags: ["accounting","finance","firm","services","team","contact"],
    allowHero: true,
  },
  ArchitectureFirmKimiPage: {
    category: "agency",
    navPageType: "home",
    tags: ["architecture","studio","minimal","project","gallery","philosophy"],
    allowHero: true,
  },
  ConstructionKimiPage: {
    category: "agency",
    navPageType: "home",
    tags: ["construction","contractor","company","projects","services","quote"],
    allowHero: true,
  },
  AboutKimiPage: {
    category: "about",
    navPageType: "about",
    tags: ["about","company","mission","story","values","team","stats","leadership","studio","kimi"],
    allowHero: true,
  },
  CorporateKimiPage: {
    category: "marketing",
    navPageType: "home",
    tags: ["corporate","enterprise","homepage","solutions","customers","investor","links"],
    allowHero: true,
  },
  LogisticsKimiPage: {
    category: "marketing",
    navPageType: "home",
    tags: ["logistics","shipping","company","tracking","services","global","reach","stats"],
    allowHero: true,
  },
  ManufacturingKimiPage: {
    category: "marketing",
    navPageType: "home",
    tags: ["industrial","manufacturing","company","capabilities","industries","served"],
    allowHero: true,
  },
  ContactKimiPage: {
    category: "contact",
    navPageType: "contact",
    tags: ["contact","support","form","reach","get","in","touch","details","office","map","faq","dark","kimi"],
    allowHero: false,
  },
  EventKimiPage: {
    category: "event",
    navPageType: "home",
    tags: [
      "event",
      "conference",
      "summit",
      "tech",
      "speakers",
      "schedule",
      "sponsors",
      "register",
      "tickets",
      "countdown",
      "dark",
      "home",
      "landing",
      "kimi",
    ],
    allowHero: true,
  },
  InvestingKimiPage: {
    category: "saas",
    navPageType: "home",
    tags: ["investing","trading","platform","portfolio","visual","markets"],
    allowHero: true,
  },
  InsuranceKimiPage: {
    category: "saas",
    navPageType: "home",
    tags: ["insurance","company","quote","coverage","options","trust"],
    allowHero: true,
  },
  LendingKimiPage: {
    category: "saas",
    navPageType: "home",
    tags: ["lending","loans","rate","calculator","works"],
    allowHero: true,
  },
  DentalKimiPage: {
    category: "marketing",
    navPageType: "home",
    tags: ["dental","practice","friendly","services","team","appointment"],
    allowHero: true,
  },
  MentalHealthKimiPage: {
    category: "marketing",
    navPageType: "home",
    tags: ["mental","health","therapy","practice","calm","services","book","session"],
    allowHero: true,
  },
  TelehealthKimiPage: {
    category: "marketing",
    navPageType: "home",
    tags: ["telehealth","platform","works","provider","network"],
    allowHero: true,
  },
  YogaStudioKimiPage: {
    category: "marketing",
    navPageType: "home",
    tags: ["yoga","meditation","studio","serene","class","schedule","pricing"],
    allowHero: true,
  },
  NutritionKimiPage: {
    category: "marketing",
    navPageType: "home",
    tags: ["nutrition","diet","coaching","plans","transformation","stories"],
    allowHero: true,
  },
  SpaWellnessKimiPage: {
    category: "marketing",
    navPageType: "home",
    tags: ["wellness","retreat","treatments","gallery","booking"],
    allowHero: true,
  },
  UniversityKimiPage: {
    category: "marketing",
    navPageType: "home",
    tags: ["university","college","programs","campus","life","apply"],
    allowHero: true,
  },
  BootcampKimiPage: {
    category: "marketing",
    navPageType: "home",
    tags: ["coding","bootcamp","curriculum","outcomes","apply"],
    allowHero: true,
  },
  TutoringKimiPage: {
    category: "marketing",
    navPageType: "home",
    tags: ["tutoring","service","subjects","tutors","book","session"],
    allowHero: true,
  },
  KidsEducationKimiPage: {
    category: "marketing",
    navPageType: "home",
    tags: ["playful","kids","learning","platform","colorful","activities"],
    allowHero: true,
  },
  PropertyListingKimiPage: {
    category: "marketing",
    navPageType: "home",
    tags: ["single","property","luxury","listing","gallery","features","tour","booking"],
    allowHero: true,
  },
  InteriorDesignKimiPage: {
    category: "agency",
    navPageType: "home",
    tags: ["interior","design","studio","elegant","project","gallery","services"],
    allowHero: true,
  },
  VacationRentalKimiPage: {
    category: "marketing",
    navPageType: "home",
    tags: ["vacation","rental","airbnb","style","listing","photos","amenities","booking"],
    allowHero: true,
  },
  CoworkingKimiPage: {
    category: "marketing",
    navPageType: "home",
    tags: ["coworking","space","spaces","amenities","pricing","tour"],
    allowHero: true,
  },
  CafeKimiPage: {
    category: "restaurant",
    navPageType: "home",
    tags: ["cozy","coffee","cafe","menu","story","location"],
    allowHero: true,
  },
  BakeryKimiPage: {
    category: "restaurant",
    navPageType: "home",
    tags: ["bakery","warm","product","showcase","order","visit"],
    allowHero: true,
  },
  BarNightclubKimiPage: {
    category: "restaurant",
    navPageType: "home",
    tags: ["nightclub","dark","vibrant","events","drinks","menu","reservations"],
    allowHero: true,
  },
  TravelAgencyKimiPage: {
    category: "marketing",
    navPageType: "home",
    tags: ["travel","agency","destinations","search","packages","reviews"],
    allowHero: true,
  },
  TourExperiencesKimiPage: {
    category: "marketing",
    navPageType: "home",
    tags: ["tours","experiences","booking","activity","reviews"],
    allowHero: true,
  },
  WineryBreweryKimiPage: {
    category: "restaurant",
    navPageType: "home",
    tags: ["winery","brewery","rustic","premium","tastings","story","visit"],
    allowHero: true,
  },
  FoodTruckKimiPage: {
    category: "restaurant",
    navPageType: "home",
    tags: ["food","truck","menu","locations","schedule","catering"],
    allowHero: true,
  },
  WeddingKimiPage: {
    category: "event",
    navPageType: "home",
    tags: ["wedding","story","schedule","rsvp","gallery"],
    allowHero: true,
  },
  MusicFestivalKimiPage: {
    category: "event",
    navPageType: "home",
    tags: ["music","festival","bold","lineup","dates","tickets"],
    allowHero: true,
  },
  WebinarKimiPage: {
    category: "event",
    navPageType: "home",
    tags: ["webinar","registration","agenda","speakers","signup"],
    allowHero: true,
  },
  ChurchKimiPage: {
    category: "marketing",
    navPageType: "home",
    tags: ["church","religious","community","warm","service","times","events","give"],
    allowHero: true,
  },
  CommunityForumKimiPage: {
    category: "marketing",
    navPageType: "home",
    tags: ["community","forum","platform","topics","join"],
    allowHero: true,
  },
  MembershipClubKimiPage: {
    category: "marketing",
    navPageType: "home",
    tags: ["membership","club","benefits","tiers","join"],
    allowHero: true,
  },
  SalonBarberKimiPage: {
    category: "marketing",
    navPageType: "home",
    tags: ["hair","salon","barbershop","services","pricing","gallery","book"],
    allowHero: true,
  },
  AutoDealershipKimiPage: {
    category: "marketing",
    navPageType: "home",
    tags: ["dealership","inventory","financing","test","drive"],
    allowHero: true,
  },
  PetVeterinaryKimiPage: {
    category: "marketing",
    navPageType: "home",
    tags: ["veterinary","clinic","services","friendly","appointment"],
    allowHero: true,
  },
  CleaningServiceKimiPage: {
    category: "marketing",
    navPageType: "home",
    tags: ["home","cleaning","service","services","pricing","book"],
    allowHero: true,
  },
  LandscapingKimiPage: {
    category: "marketing",
    navPageType: "home",
    tags: ["landscaping","company","portfolio","services","quote"],
    allowHero: true,
  },
  PlumbingHvacKimiPage: {
    category: "marketing",
    navPageType: "home",
    tags: ["plumbing","hvac","service","services","trust","badges","emergency"],
    allowHero: true,
  },
  EventPlannerKimiPage: {
    category: "agency",
    navPageType: "home",
    tags: ["event","planning","company","elegant","services","gallery","inquiry"],
    allowHero: true,
  },
  ComingSoonKimiPage: {
    category: "marketing",
    navPageType: "home",
    tags: ["coming","soon","waitlist","countdown","email","capture"],
    allowHero: true,
  },
  JobBoardKimiPage: {
    category: "marketing",
    navPageType: "list",
    tags: ["board","careers","search","listings","categories"],
    allowHero: true,
  },
  DirectoryKimiPage: {
    category: "marketing",
    navPageType: "list",
    tags: ["local","business","directory","listings","homepage","search","category","tiles"],
    allowHero: true,
  },
  DatingAppKimiPage: {
    category: "saas",
    navPageType: "home",
    tags: ["dating","warm","works","download"],
    allowHero: true,
  },
  CrowdfundingKimiPage: {
    category: "marketing",
    navPageType: "home",
    tags: ["crowdfunding","campaign","progress","story","rewards","tiers"],
    allowHero: true,
  },
  LinkInBioKimiPage: {
    category: "portfolio",
    navPageType: "home",
    tags: ["link","personal","avatar","buttons"],
    allowHero: true,
  },
  TeamKimiPage: {
    category: "about",
    navPageType: "team",
    tags: ["company","team","people","leadership","culture"],
    allowHero: true,
  },
  FaqKimiPage: {
    category: "about",
    navPageType: "index",
    tags: ["help","center","search","topics","accordion"],
    allowHero: false,
  },
  FlightSimulatorKimiPage: {
    category: "game",
    navPageType: "home",
    tags: ["flight","simulator","3d","three.js","game","interactive","aerial","terrain","single-player"],
    allowHero: true,
  },
  TestimonialsKimiPage: {
    category: "marketing",
    navPageType: "home",
    tags: ["testimonials","case","studies","reviews","quotes","logos","metrics"],
    allowHero: true,
  },
  AccountingFirmKimiPage2: {
    category: "agency",
    navPageType: "home",
    tags: ["accounting","finance","firm","services","team","contact"],
    allowHero: true,
  },
  AgencyKimiPage2: {
    category: "agency",
    navPageType: "home",
    tags: ["agency", "studio", "creative", "design", "portfolio", "work", "services", "home", "kimi"],
    allowHero: true,
  },
  AiProductKimiPage2: {
    category: "saas",
    navPageType: "home",
    tags: ["product","generative","writing","assistant"],
    allowHero: true,
  },
  AnalyticsKimiPage2: {
    category: "dashboard",
    navPageType: "dashboard",
    tags: ["saas","analytics","dashboard","sidebar","charts","data","table"],
    allowHero: false,
  },
  ArchitectureFirmKimiPage2: {
    category: "agency",
    navPageType: "home",
    tags: ["architecture","studio","minimal","project","gallery","philosophy"],
    allowHero: true,
  },
  BeautyStoreKimiPage2: {
    category: "ecommerce",
    navPageType: "home",
    tags: ["beauty","cosmetics","store","homepage","clean","pastel","bestsellers"],
    allowHero: true,
  },
  BlogKimiPage2: {
    category: "blog",
    navPageType: "index",
    tags: ["blog", "articles", "editorial", "magazine", "posts", "index", "no-hero", "kimi"],
    allowHero: false,
  },
  BlogPostKimiPage2: {
    category: "blog",
    navPageType: "detail",
    tags: ["readable","blog","article","title","author","cover","image","long"],
    allowHero: false,
  },
  BootcampKimiPage2: {
    category: "marketing",
    navPageType: "home",
    tags: ["coding","bootcamp","curriculum","outcomes","apply"],
    allowHero: true,
  },
  CloudInfraKimiPage2: {
    category: "saas",
    navPageType: "home",
    tags: ["cloud","infrastructure","hosting","platform","pricing","usage"],
    allowHero: true,
  },
  ConstructionKimiPage2: {
    category: "agency",
    navPageType: "home",
    tags: ["construction","contractor","company","projects","services","quote"],
    allowHero: true,
  },
  ConsultingKimiPage2: {
    category: "agency",
    navPageType: "home",
    tags: ["management","consulting","firm","corporate","trustworthy","services","insights"],
    allowHero: true,
  },
  CorporateKimiPage2: {
    category: "marketing",
    navPageType: "home",
    tags: ["corporate","enterprise","homepage","solutions","customers","investor","links"],
    allowHero: true,
  },
  CrmKimiPage2: {
    category: "saas",
    navPageType: "home",
    tags: ["sales","platform","pipeline","visual","integrations"],
    allowHero: true,
  },
  CryptoKimiPage2: {
    category: "saas",
    navPageType: "home",
    tags: ["crypto","platform","token","visual","live","stats","roadmap"],
    allowHero: true,
  },
  CybersecurityKimiPage2: {
    category: "saas",
    navPageType: "home",
    tags: ["cybersecurity","platform","trust","forward","threat","stats","enterprise","logos"],
    allowHero: true,
  },
  DentalKimiPage2: {
    category: "marketing",
    navPageType: "home",
    tags: ["dental","practice","friendly","services","team","appointment"],
    allowHero: true,
  },
  DevToolKimiPage2: {
    category: "saas",
    navPageType: "home",
    tags: ["developer","tool","platform","code","samples","integration","logos"],
    allowHero: true,
  },
  DocsKimiPage2: {
    category: "saas",
    navPageType: "index",
    tags: ["developer","documentation","sidebar","search","getting","started","code","block"],
    allowHero: false,
  },
  ShopKimiPage2: {
    category: "ecommerce",
    navPageType: "list",
    tags: ["ecommerce", "shop", "store", "sneakers", "products", "retail", "catalog", "kimi"],
    allowHero: true,
  },
  FashionStoreKimiPage2: {
    category: "ecommerce",
    navPageType: "home",
    tags: ["fashion","apparel","online","store","homepage","editorial","lookbook","driven"],
    allowHero: true,
  },
  FilmDirectorKimiPage2: {
    category: "portfolio",
    navPageType: "home",
    tags: ["film","director","videographer","portfolio","cinematic","reel"],
    allowHero: true,
  },
  FintechKimiPage2: {
    category: "saas",
    navPageType: "home",
    tags: ["fintech","digital","wallet","banking","card","visual","security","features"],
    allowHero: true,
  },
  FoodDeliveryKimiPage2: {
    category: "ecommerce",
    navPageType: "home",
    tags: ["food","delivery","restaurant","tiles","order"],
    allowHero: true,
  },
  FurnitureStoreKimiPage2: {
    category: "ecommerce",
    navPageType: "home",
    tags: ["furniture","home","decor","store","homepage","warm","minimal","room"],
    allowHero: true,
  },
  HealthcareKimiPage2: {
    category: "marketing",
    navPageType: "home",
    tags: ["healthcare","clinic","services","doctors","testimonials","booking"],
    allowHero: true,
  },
  IllustratorKimiPage2: {
    category: "portfolio",
    navPageType: "home",
    tags: ["illustrator","artist","portfolio","playful","colorful","work","gallery","shop"],
    allowHero: true,
  },
  InsuranceKimiPage2: {
    category: "saas",
    navPageType: "home",
    tags: ["insurance","company","quote","coverage","options","trust"],
    allowHero: true,
  },

  InvestingKimiPage2: {
    category: "saas",
    navPageType: "home",
    tags: ["investing","trading","platform","portfolio","visual","markets"],
    allowHero: true,
  },
  JewelryStoreKimiPage2: {
    category: "ecommerce",
    navPageType: "home",
    tags: ["luxury","jewelry","store","homepage","elegant","dark","piece","collections"],
    allowHero: true,
  },
  LawFirmKimiPage2: {
    category: "agency",
    navPageType: "home",
    tags: ["firm","authoritative","practice","areas","attorneys","consultation"],
    allowHero: true,
  },
  LendingKimiPage2: {
    category: "saas",
    navPageType: "home",
    tags: ["lending","loans","rate","calculator","works"],
    allowHero: true,
  },
  LogisticsKimiPage2: {
    category: "marketing",
    navPageType: "home",
    tags: ["logistics","shipping","company","tracking","services","global","reach","stats"],
    allowHero: true,
  },
  ManufacturingKimiPage2: {
    category: "marketing",
    navPageType: "home",
    tags: ["industrial","manufacturing","company","capabilities","industries","served"],
    allowHero: true,
  },
  MarketingAgencyKimiPage2: {
    category: "agency",
    navPageType: "home",
    tags: ["marketing","growth","agency","results","stats","services","case","studies"],
    allowHero: true,
  },
  MarketplaceKimiPage2: {
    category: "ecommerce",
    navPageType: "list",
    tags: ["multi","vendor","marketplace","homepage","categories","featured","sellers","trending"],
    allowHero: true,
  },
  MentalHealthKimiPage2: {
    category: "marketing",
    navPageType: "home",
    tags: ["mental","health","therapy","practice","calm","services","book","session"],
    allowHero: true,
  },
  MobileAppKimiPage2: {
    category: "saas",
    navPageType: "home",
    tags: ["mobile","habit","tracking","phone","mockups","store","badges"],
    allowHero: true,
  },
  MusicArtistKimiPage2: {
    category: "portfolio",
    navPageType: "home",
    tags: ["music","artist","band","latest","release","tour","dates"],
    allowHero: true,
  },
  NewsKimiPage2: {
    category: "blog",
    navPageType: "index",
    tags: ["news","magazine","homepage","stories","category","trending","sidebar"],
    allowHero: false,
  },
  NewsletterKimiPage2: {
    category: "marketing",
    navPageType: "home",
    tags: ["substack","style","newsletter","subscribe","form","what","recent","issues"],
    allowHero: true,
  },
  NoCodeKimiPage2: {
    category: "saas",
    navPageType: "home",
    tags: ["code","builder","drag","drop","visual","templates","gallery"],
    allowHero: true,
  },
  NutritionKimiPage2: {
    category: "marketing",
    navPageType: "home",
    tags: ["nutrition","diet","coaching","plans","transformation","stories"],
    allowHero: true,
  },
  PhotographyKimiPage2: {
    category: "portfolio",
    navPageType: "gallery",
    tags: ["photography","portfolio","full","bleed","masonry","gallery","services","contact"],
    allowHero: true,
  },
  PodcastKimiPage2: {
    category: "blog",
    navPageType: "home",
    tags: ["podcast","show","play","button","latest","episodes","list","subscribe"],
    allowHero: true,
  },
  PortfolioKimiPage2: {
    category: "portfolio",
    navPageType: "home",
    tags: [
      "portfolio",
      "3d-artist",
      "motion-designer",
      "art-director",
      "cgi",
      "vfx",
      "animator",
      "creative",
      "dark",
      "cinematic",
      "showcase",
      "work",
      "home",
      "kimi",
    ],
    allowHero: true,
  },
  PortfolioDevKimiPage2: {
    category: "portfolio",
    navPageType: "home",
    tags: ["software","developer","portfolio","projects","skills","open","source","work"],
    allowHero: true,
  },
  ProductDetailKimiPage2: {
    category: "ecommerce",
    navPageType: "detail",
    tags: ["commerce","product","detail","image","gallery","size","color","selectors"],
    allowHero: false,
  },
  RealEstateKimiPage2: {
    category: "marketing",
    navPageType: "home",
    tags: ["estate","agency","property","search","listings","agents"],
    allowHero: true,
  },
  ResumeCvKimiPage2: {
    category: "portfolio",
    navPageType: "home",
    tags: ["personal","resume","experience","timeline","skills"],
    allowHero: true,
  },
  SaasKimiPage2: {
    category: "saas",
    navPageType: "home",
    tags: [
      "saas",
      "software",
      "ai",
      "product",
      "app",
      "b2b",
      "platform",
      "scheduling",
      "automation",
      "productivity",
      "landing",
      "home",
      "pricing",
      "social-proof",
      "kimi",
    ],
    allowHero: true,
  },
  SpaWellnessKimiPage2: {
    category: "marketing",
    navPageType: "home",
    tags: ["wellness","retreat","treatments","gallery","booking"],
    allowHero: true,
  },
  SubscriptionBoxKimiPage2: {
    category: "ecommerce",
    navPageType: "home",
    tags: ["subscription","coffee","works","plan","tiers"],
    allowHero: true,
  },
  UniversityKimiPage2: {
    category: "marketing",
    navPageType: "home",
    tags: ["university","college","programs","campus","life","apply"],
    allowHero: true,
  },
  VideoStreamingKimiPage2: {
    category: "marketing",
    navPageType: "home",
    tags: ["video","streaming","service","featured","content","rows","plan"],
    allowHero: true,
  },
  WriterAuthorKimiPage2: {
    category: "portfolio",
    navPageType: "home",
    tags: ["author","book","about","reviews","links"],
    allowHero: true,
  },
  YogaStudioKimiPage2: {
    category: "marketing",
    navPageType: "home",
    tags: ["yoga","meditation","studio","serene","class","schedule","pricing"],
    allowHero: true,
  },

  AiProductKimiPage10: {
    category: "saas",
    navPageType: "home",
    tags: ["product","generative","writing","assistant"],
    allowHero: true,
  },
  AiProductKimiPage3: {
    category: "saas",
    navPageType: "home",
    tags: ["product","generative","writing","assistant"],
    allowHero: true,
  },
  AiProductKimiPage4: {
    category: "saas",
    navPageType: "home",
    tags: ["product","generative","writing","assistant"],
    allowHero: true,
  },
  AiProductKimiPage6: {
    category: "saas",
    navPageType: "home",
    tags: ["product","generative","writing","assistant"],
    allowHero: true,
  },
  AiProductKimiPage7: {
    category: "saas",
    navPageType: "home",
    tags: ["product","generative","writing","assistant"],
    allowHero: true,
  },
  AiProductKimiPage8: {
    category: "saas",
    navPageType: "home",
    tags: ["product","generative","writing","assistant"],
    allowHero: true,
  },
  BarNightclubKimiPage2: {
    category: "restaurant",
    navPageType: "home",
    tags: ["nightclub","dark","vibrant","events","drinks","menu","reservations"],
    allowHero: true,
  },
  DevToolKimiPage10: {
    category: "saas",
    navPageType: "home",
    tags: ["developer","tool","platform","code","samples","integration","logos"],
    allowHero: true,
  },
  DevToolKimiPage3: {
    category: "saas",
    navPageType: "home",
    tags: ["developer","tool","platform","code","samples","integration","logos"],
    allowHero: true,
  },
  DevToolKimiPage4: {
    category: "saas",
    navPageType: "home",
    tags: ["developer","tool","platform","code","samples","integration","logos"],
    allowHero: true,
  },
  DevToolKimiPage5: {
    category: "saas",
    navPageType: "home",
    tags: ["developer","tool","platform","code","samples","integration","logos"],
    allowHero: true,
  },
  DevToolKimiPage6: {
    category: "saas",
    navPageType: "home",
    tags: ["developer","tool","platform","code","samples","integration","logos"],
    allowHero: true,
  },
  DevToolKimiPage7: {
    category: "saas",
    navPageType: "home",
    tags: ["developer","tool","platform","code","samples","integration","logos"],
    allowHero: true,
  },
  DevToolKimiPage8: {
    category: "saas",
    navPageType: "home",
    tags: ["developer","tool","platform","code","samples","integration","logos"],
    allowHero: true,
  },
  DevToolKimiPage9: {
    category: "saas",
    navPageType: "home",
    tags: ["developer","tool","platform","code","samples","integration","logos"],
    allowHero: true,
  },
  DocsKimiPage3: {
    category: "saas",
    navPageType: "index",
    tags: ["developer","documentation","sidebar","search","getting","started","code","block"],
    allowHero: false,
  },
  DocsKimiPage4: {
    category: "saas",
    navPageType: "index",
    tags: ["developer","documentation","sidebar","search","getting","started","code","block"],
    allowHero: false,
  },
  DocsKimiPage5: {
    category: "saas",
    navPageType: "index",
    tags: ["developer","documentation","sidebar","search","getting","started","code","block"],
    allowHero: false,
  },
  ElectronicsStoreKimiPage2: {
    category: "ecommerce",
    navPageType: "home",
    tags: ["electronics","gadgets","online","store","homepage","deals","product"],
    allowHero: true,
  },
  FitnessKimiPage2: {
    category: "marketing",
    navPageType: "home",
    tags: ["fitness","studio","classes","schedule","membership","tiers","trainers"],
    allowHero: true,
  },
  KidsEducationKimiPage2: {
    category: "marketing",
    navPageType: "home",
    tags: ["playful","kids","learning","platform","colorful","activities"],
    allowHero: true,
  },
  KnowledgeBaseKimiPage2: {
    category: "saas",
    navPageType: "home",
    tags: ["help","center","knowledge","base","home","search","popular","topics"],
    allowHero: true,
  },
  MobileAppKimiPage10: {
    category: "saas",
    navPageType: "home",
    tags: ["mobile","habit","tracking","phone","mockups","store","badges"],
    allowHero: true,
  },
  MobileAppKimiPage3: {
    category: "saas",
    navPageType: "home",
    tags: ["mobile","habit","tracking","phone","mockups","store","badges"],
    allowHero: true,
  },
  MobileAppKimiPage4: {
    category: "saas",
    navPageType: "home",
    tags: ["mobile","habit","tracking","phone","mockups","store","badges"],
    allowHero: true,
  },
  MobileAppKimiPage5: {
    category: "saas",
    navPageType: "home",
    tags: ["mobile","habit","tracking","phone","mockups","store","badges"],
    allowHero: true,
  },
  MobileAppKimiPage6: {
    category: "saas",
    navPageType: "home",
    tags: ["mobile","habit","tracking","phone","mockups","store","badges"],
    allowHero: true,
  },
  MobileAppKimiPage7: {
    category: "saas",
    navPageType: "home",
    tags: ["mobile","habit","tracking","phone","mockups","store","badges"],
    allowHero: true,
  },
  MobileAppKimiPage8: {
    category: "saas",
    navPageType: "home",
    tags: ["mobile","habit","tracking","phone","mockups","store","badges"],
    allowHero: true,
  },
  MobileAppKimiPage9: {
    category: "saas",
    navPageType: "home",
    tags: ["mobile","habit","tracking","phone","mockups","store","badges"],
    allowHero: true,
  },
  OnlineCourseKimiPage2: {
    category: "marketing",
    navPageType: "home",
    tags: ["online","course","popular","courses","instructors","signup"],
    allowHero: true,
  },
  PropertyListingKimiPage2: {
    category: "marketing",
    navPageType: "home",
    tags: ["single","property","luxury","listing","gallery","features","tour","booking"],
    allowHero: true,
  },
  RestaurantKimiPage2: {
    category: "restaurant",
    navPageType: "home",
    tags: [
      "restaurant",
      "ramen",
      "izakaya",
      "japanese",
      "food",
      "menu",
      "dining",
      "reservation",
      "dark",
      "image-led",
      "home",
      "landing",
      "kimi",
    ],
    allowHero: true,
  },
  SaasKimiPage10: {
    category: "saas",
    navPageType: "home",
    tags: [
      "saas",
      "software",
      "ai",
      "product",
      "app",
      "b2b",
      "platform",
      "scheduling",
      "automation",
      "productivity",
      "landing",
      "home",
      "pricing",
      "social-proof",
      "kimi",
    ],
    allowHero: true,
  },
  SaasKimiPage3: {
    category: "saas",
    navPageType: "home",
    tags: [
      "saas",
      "software",
      "ai",
      "product",
      "app",
      "b2b",
      "platform",
      "scheduling",
      "automation",
      "productivity",
      "landing",
      "home",
      "pricing",
      "social-proof",
      "kimi",
    ],
    allowHero: true,
  },
  SaasKimiPage4: {
    category: "saas",
    navPageType: "home",
    tags: [
      "saas",
      "software",
      "ai",
      "product",
      "app",
      "b2b",
      "platform",
      "scheduling",
      "automation",
      "productivity",
      "landing",
      "home",
      "pricing",
      "social-proof",
      "kimi",
    ],
    allowHero: true,
  },
  SaasKimiPage5: {
    category: "saas",
    navPageType: "home",
    tags: [
      "saas",
      "software",
      "ai",
      "product",
      "app",
      "b2b",
      "platform",
      "scheduling",
      "automation",
      "productivity",
      "landing",
      "home",
      "pricing",
      "social-proof",
      "kimi",
    ],
    allowHero: true,
  },
  SaasKimiPage6: {
    category: "saas",
    navPageType: "home",
    tags: [
      "saas",
      "software",
      "ai",
      "product",
      "app",
      "b2b",
      "platform",
      "scheduling",
      "automation",
      "productivity",
      "landing",
      "home",
      "pricing",
      "social-proof",
      "kimi",
    ],
    allowHero: true,
  },
  SaasKimiPage7: {
    category: "saas",
    navPageType: "home",
    tags: [
      "saas",
      "software",
      "ai",
      "product",
      "app",
      "b2b",
      "platform",
      "scheduling",
      "automation",
      "productivity",
      "landing",
      "home",
      "pricing",
      "social-proof",
      "kimi",
    ],
    allowHero: true,
  },
  SaasKimiPage8: {
    category: "saas",
    navPageType: "home",
    tags: [
      "saas",
      "software",
      "ai",
      "product",
      "app",
      "b2b",
      "platform",
      "scheduling",
      "automation",
      "productivity",
      "landing",
      "home",
      "pricing",
      "social-proof",
      "kimi",
    ],
    allowHero: true,
  },
  SaasKimiPage9: {
    category: "saas",
    navPageType: "home",
    tags: [
      "saas",
      "software",
      "ai",
      "product",
      "app",
      "b2b",
      "platform",
      "scheduling",
      "automation",
      "productivity",
      "landing",
      "home",
      "pricing",
      "social-proof",
      "kimi",
    ],
    allowHero: true,
  },
  TelehealthKimiPage2: {
    category: "marketing",
    navPageType: "home",
    tags: ["telehealth","platform","works","provider","network"],
    allowHero: true,
  },
  TutoringKimiPage2: {
    category: "marketing",
    navPageType: "home",
    tags: ["tutoring","service","subjects","tutors","book","session"],
    allowHero: true,
  },
  VacationRentalKimiPage2: {
    category: "marketing",
    navPageType: "home",
    tags: ["vacation","rental","airbnb","style","listing","photos","amenities","booking"],
    allowHero: true,
  },

  EducationKimiPage: {
    category: "marketing",
    navPageType: "home",
    tags: ["education","academy","learning","platform","courses","outcomes","instructors","enrollment","institution","school","programs","admissions","campus","life","faculty"],
    allowHero: true,
  },
  AboutKimiPage2: {
    category: "about",
    navPageType: "about",
    tags: ["about","company","mission","story","values","team","stats","leadership","studio","kimi"],
    allowHero: true,
  },
  AccountingFirmKimiPage3: {
    category: "agency",
    navPageType: "home",
    tags: ["accounting","finance","firm","services","team","contact"],
    allowHero: true,
  },
  AgencyKimiPage3: {
    category: "agency",
    navPageType: "home",
    tags: ["agency", "studio", "creative", "design", "portfolio", "work", "services", "home", "kimi"],
    allowHero: true,
  },
  AgencyKimiPage4: {
    category: "agency",
    navPageType: "home",
    tags: ["agency", "studio", "creative", "design", "portfolio", "work", "services", "home", "kimi"],
    allowHero: true,
  },
  AnalyticsKimiPage3: {
    category: "dashboard",
    navPageType: "dashboard",
    tags: ["saas","analytics","dashboard","sidebar","charts","data","table"],
    allowHero: false,
  },
  ArchitectureFirmKimiPage3: {
    category: "agency",
    navPageType: "home",
    tags: ["architecture","studio","minimal","project","gallery","philosophy"],
    allowHero: true,
  },
  AutoDealershipKimiPage2: {
    category: "marketing",
    navPageType: "home",
    tags: ["dealership","inventory","financing","test","drive"],
    allowHero: true,
  },
  BakeryKimiPage2: {
    category: "restaurant",
    navPageType: "home",
    tags: ["bakery","warm","product","showcase","order","visit"],
    allowHero: true,
  },
  BeautyStoreKimiPage3: {
    category: "ecommerce",
    navPageType: "home",
    tags: ["beauty","cosmetics","store","homepage","clean","pastel","bestsellers"],
    allowHero: true,
  },
  BlogKimiPage3: {
    category: "blog",
    navPageType: "index",
    tags: ["blog", "articles", "editorial", "magazine", "posts", "index", "no-hero", "kimi"],
    allowHero: false,
  },
  BlogPostKimiPage3: {
    category: "blog",
    navPageType: "detail",
    tags: ["readable","blog","article","title","author","cover","image","long"],
    allowHero: false,
  },
  BlogPostKimiPage4: {
    category: "blog",
    navPageType: "detail",
    tags: ["readable","blog","article","title","author","cover","image","long"],
    allowHero: false,
  },
  BootcampKimiPage3: {
    category: "marketing",
    navPageType: "home",
    tags: ["coding","bootcamp","curriculum","outcomes","apply"],
    allowHero: true,
  },
  CafeKimiPage2: {
    category: "restaurant",
    navPageType: "home",
    tags: ["cozy","coffee","cafe","menu","story","location"],
    allowHero: true,
  },
  ChurchKimiPage2: {
    category: "marketing",
    navPageType: "home",
    tags: ["church","religious","community","warm","service","times","events","give"],
    allowHero: true,
  },
  CleaningServiceKimiPage2: {
    category: "marketing",
    navPageType: "home",
    tags: ["home","cleaning","service","services","pricing","book"],
    allowHero: true,
  },
  CloudInfraKimiPage3: {
    category: "saas",
    navPageType: "home",
    tags: ["cloud","infrastructure","hosting","platform","pricing","usage"],
    allowHero: true,
  },
  ComingSoonKimiPage2: {
    category: "marketing",
    navPageType: "home",
    tags: ["coming","soon","waitlist","countdown","email","capture"],
    allowHero: true,
  },
  CommunityForumKimiPage2: {
    category: "marketing",
    navPageType: "home",
    tags: ["community","forum","platform","topics","join"],
    allowHero: true,
  },
  ConstructionKimiPage3: {
    category: "agency",
    navPageType: "home",
    tags: ["construction","contractor","company","projects","services","quote"],
    allowHero: true,
  },
  ConsultingKimiPage3: {
    category: "agency",
    navPageType: "home",
    tags: ["management","consulting","firm","corporate","trustworthy","services","insights"],
    allowHero: true,
  },
  ConsultingKimiPage4: {
    category: "agency",
    navPageType: "home",
    tags: ["management","consulting","firm","corporate","trustworthy","services","insights"],
    allowHero: true,
  },
  ContactKimiPage2: {
    category: "contact",
    navPageType: "contact",
    tags: ["contact","support","form","reach","get","in","touch","details","office","map","faq","dark","kimi"],
    allowHero: false,
  },
  CorporateKimiPage3: {
    category: "marketing",
    navPageType: "home",
    tags: ["corporate","enterprise","homepage","solutions","customers","investor","links"],
    allowHero: true,
  },
  CoworkingKimiPage2: {
    category: "marketing",
    navPageType: "home",
    tags: ["coworking","space","spaces","amenities","pricing","tour"],
    allowHero: true,
  },
  CoworkingKimiPage3: {
    category: "marketing",
    navPageType: "home",
    tags: ["coworking","space","spaces","amenities","pricing","tour"],
    allowHero: true,
  },
  CrmKimiPage3: {
    category: "saas",
    navPageType: "home",
    tags: ["sales","platform","pipeline","visual","integrations"],
    allowHero: true,
  },
  CrowdfundingKimiPage2: {
    category: "marketing",
    navPageType: "home",
    tags: ["crowdfunding","campaign","progress","story","rewards","tiers"],
    allowHero: true,
  },
  CryptoKimiPage3: {
    category: "saas",
    navPageType: "home",
    tags: ["crypto","platform","token","visual","live","stats","roadmap"],
    allowHero: true,
  },
  CybersecurityKimiPage3: {
    category: "saas",
    navPageType: "home",
    tags: ["cybersecurity","platform","trust","forward","threat","stats","enterprise","logos"],
    allowHero: true,
  },
  DatingAppKimiPage2: {
    category: "saas",
    navPageType: "home",
    tags: ["dating","warm","works","download"],
    allowHero: true,
  },
  DentalKimiPage3: {
    category: "marketing",
    navPageType: "home",
    tags: ["dental","practice","friendly","services","team","appointment"],
    allowHero: true,
  },
  DirectoryKimiPage2: {
    category: "marketing",
    navPageType: "list",
    tags: ["local","business","directory","listings","homepage","search","category","tiles"],
    allowHero: true,
  },
  EcommerceKimiPage3: {
    category: "ecommerce",
    navPageType: "home",
    tags: ["ecommerce", "shop", "store", "sneakers", "products", "retail", "catalog", "kimi"],
    allowHero: true,
  },
  EducationKimiPage2: {
    category: "marketing",
    navPageType: "home",
    tags: ["education","academy","learning","platform","courses","outcomes","instructors","enrollment"],
    allowHero: true,
  },
  EducationKimiPage3: {
    category: "marketing",
    navPageType: "home",
    tags: ["education","academy","learning","platform","courses","outcomes","instructors","enrollment"],
    allowHero: true,
  },
  ElectronicsStoreKimiPage3: {
    category: "ecommerce",
    navPageType: "home",
    tags: ["electronics","gadgets","online","store","homepage","deals","product"],
    allowHero: true,
  },
  EventKimiPage2: {
    category: "event",
    navPageType: "home",
    tags: [
      "event",
      "conference",
      "summit",
      "tech",
      "speakers",
      "schedule",
      "sponsors",
      "register",
      "tickets",
      "countdown",
      "dark",
      "home",
      "landing",
      "kimi",
    ],
    allowHero: true,
  },
  EventPlannerKimiPage2: {
    category: "agency",
    navPageType: "home",
    tags: ["event","planning","company","elegant","services","gallery","inquiry"],
    allowHero: true,
  },
  FaqKimiPage2: {
    category: "about",
    navPageType: "index",
    tags: ["help","center","search","topics","accordion"],
    allowHero: false,
  },
  FashionStoreKimiPage3: {
    category: "ecommerce",
    navPageType: "home",
    tags: ["fashion","apparel","online","store","homepage","editorial","lookbook","driven"],
    allowHero: true,
  },
  FilmDirectorKimiPage3: {
    category: "portfolio",
    navPageType: "home",
    tags: ["film","director","videographer","portfolio","cinematic","reel"],
    allowHero: true,
  },
  FintechKimiPage3: {
    category: "saas",
    navPageType: "home",
    tags: ["fintech","digital","wallet","banking","card","visual","security","features"],
    allowHero: true,
  },
  FitnessKimiPage3: {
    category: "marketing",
    navPageType: "home",
    tags: ["fitness","studio","classes","schedule","membership","tiers","trainers"],
    allowHero: true,
  },
  FoodDeliveryKimiPage3: {
    category: "ecommerce",
    navPageType: "home",
    tags: ["food","delivery","restaurant","tiles","order"],
    allowHero: true,
  },
  FoodTruckKimiPage2: {
    category: "restaurant",
    navPageType: "home",
    tags: ["food","truck","menu","locations","schedule","catering"],
    allowHero: true,
  },
  FurnitureStoreKimiPage3: {
    category: "ecommerce",
    navPageType: "home",
    tags: ["furniture","home","decor","store","homepage","warm","minimal","room"],
    allowHero: true,
  },
  HealthcareKimiPage3: {
    category: "marketing",
    navPageType: "home",
    tags: ["healthcare","clinic","services","doctors","testimonials","booking"],
    allowHero: true,
  },
  HotelResortKimiPage2: {
    category: "marketing",
    navPageType: "home",
    tags: ["luxury","hotel","resort","rooms","amenities","gallery","booking"],
    allowHero: true,
  },
  IllustratorKimiPage3: {
    category: "portfolio",
    navPageType: "home",
    tags: ["illustrator","artist","portfolio","playful","colorful","work","gallery","shop"],
    allowHero: true,
  },
  InsuranceKimiPage3: {
    category: "saas",
    navPageType: "home",
    tags: ["insurance","company","quote","coverage","options","trust"],
    allowHero: true,
  },
  InteriorDesignKimiPage2: {
    category: "agency",
    navPageType: "home",
    tags: ["interior","design","studio","elegant","project","gallery","services"],
    allowHero: true,
  },
  InteriorDesignKimiPage3: {
    category: "agency",
    navPageType: "home",
    tags: ["interior","design","studio","elegant","project","gallery","services"],
    allowHero: true,
  },
  InvestingKimiPage3: {
    category: "saas",
    navPageType: "home",
    tags: ["investing","trading","platform","portfolio","visual","markets"],
    allowHero: true,
  },
  JewelryStoreKimiPage3: {
    category: "ecommerce",
    navPageType: "home",
    tags: ["luxury","jewelry","store","homepage","elegant","dark","piece","collections"],
    allowHero: true,
  },
  JobBoardKimiPage2: {
    category: "marketing",
    navPageType: "list",
    tags: ["board","careers","search","listings","categories"],
    allowHero: true,
  },
  KidsEducationKimiPage3: {
    category: "marketing",
    navPageType: "home",
    tags: ["playful","kids","learning","platform","colorful","activities"],
    allowHero: true,
  },
  KnowledgeBaseKimiPage3: {
    category: "saas",
    navPageType: "home",
    tags: ["help","center","knowledge","base","home","search","popular","topics"],
    allowHero: true,
  },
  LandscapingKimiPage2: {
    category: "marketing",
    navPageType: "home",
    tags: ["landscaping","company","portfolio","services","quote"],
    allowHero: true,
  },
  LawFirmKimiPage3: {
    category: "agency",
    navPageType: "home",
    tags: ["firm","authoritative","practice","areas","attorneys","consultation"],
    allowHero: true,
  },
  LendingKimiPage3: {
    category: "saas",
    navPageType: "home",
    tags: ["lending","loans","rate","calculator","works"],
    allowHero: true,
  },
  LinkInBioKimiPage2: {
    category: "portfolio",
    navPageType: "home",
    tags: ["link","personal","avatar","buttons"],
    allowHero: true,
  },
  LogisticsKimiPage3: {
    category: "marketing",
    navPageType: "home",
    tags: ["logistics","shipping","company","tracking","services","global","reach","stats"],
    allowHero: true,
  },
  ManufacturingKimiPage3: {
    category: "marketing",
    navPageType: "home",
    tags: ["industrial","manufacturing","company","capabilities","industries","served"],
    allowHero: true,
  },
  MarketingAgencyKimiPage3: {
    category: "agency",
    navPageType: "home",
    tags: ["marketing","growth","agency","results","stats","services","case","studies"],
    allowHero: true,
  },
  MarketingKimiPage2: {
    category: "marketing",
    navPageType: "home",
    tags: ["marketing", "landing", "saas", "product", "premium", "hero", "home", "kimi"],
    allowHero: true,
  },
  MarketplaceKimiPage3: {
    category: "ecommerce",
    navPageType: "list",
    tags: ["multi","vendor","marketplace","homepage","categories","featured","sellers","trending"],
    allowHero: true,
  },
  MembershipClubKimiPage2: {
    category: "marketing",
    navPageType: "home",
    tags: ["membership","club","benefits","tiers","join"],
    allowHero: true,
  },
  MentalHealthKimiPage3: {
    category: "marketing",
    navPageType: "home",
    tags: ["mental","health","therapy","practice","calm","services","book","session"],
    allowHero: true,
  },
  MusicArtistKimiPage3: {
    category: "portfolio",
    navPageType: "home",
    tags: ["music","artist","band","latest","release","tour","dates"],
    allowHero: true,
  },
  MusicFestivalKimiPage2: {
    category: "event",
    navPageType: "home",
    tags: ["music","festival","bold","lineup","dates","tickets"],
    allowHero: true,
  },
  NewsKimiPage3: {
    category: "blog",
    navPageType: "index",
    tags: ["news","magazine","homepage","stories","category","trending","sidebar"],
    allowHero: false,
  },
  NewsletterKimiPage3: {
    category: "marketing",
    navPageType: "home",
    tags: ["substack","style","newsletter","subscribe","form","what","recent","issues"],
    allowHero: true,
  },
  NoCodeKimiPage3: {
    category: "saas",
    navPageType: "home",
    tags: ["code","builder","drag","drop","visual","templates","gallery"],
    allowHero: true,
  },
  NonprofitKimiPage2: {
    category: "marketing",
    navPageType: "home",
    tags: ["nonprofit","charity","mission","impact","stats","programs","donate"],
    allowHero: true,
  },
  NutritionKimiPage3: {
    category: "marketing",
    navPageType: "home",
    tags: ["nutrition","diet","coaching","plans","transformation","stories"],
    allowHero: true,
  },
  OnlineCourseKimiPage3: {
    category: "marketing",
    navPageType: "home",
    tags: ["online","course","popular","courses","instructors","signup"],
    allowHero: true,
  },
  PetVeterinaryKimiPage2: {
    category: "marketing",
    navPageType: "home",
    tags: ["veterinary","clinic","services","friendly","appointment"],
    allowHero: true,
  },
  PhotographyKimiPage3: {
    category: "portfolio",
    navPageType: "gallery",
    tags: ["photography","portfolio","full","bleed","masonry","gallery","services","contact"],
    allowHero: true,
  },
  PlumbingHvacKimiPage2: {
    category: "marketing",
    navPageType: "home",
    tags: ["plumbing","hvac","service","services","trust","badges","emergency"],
    allowHero: true,
  },
  PodcastKimiPage3: {
    category: "blog",
    navPageType: "home",
    tags: ["podcast","show","play","button","latest","episodes","list","subscribe"],
    allowHero: true,
  },
  PortfolioDevKimiPage3: {
    category: "portfolio",
    navPageType: "home",
    tags: ["software","developer","portfolio","projects","skills","open","source","work"],
    allowHero: true,
  },
  PortfolioDevKimiPage4: {
    category: "portfolio",
    navPageType: "home",
    tags: ["software","developer","portfolio","projects","skills","open","source","work"],
    allowHero: true,
  },
  PortfolioKimiPage3: {
    category: "portfolio",
    navPageType: "home",
    tags: [
      "portfolio",
      "3d-artist",
      "motion-designer",
      "art-director",
      "cgi",
      "vfx",
      "animator",
      "creative",
      "dark",
      "cinematic",
      "showcase",
      "work",
      "home",
      "kimi",
    ],
    allowHero: true,
  },
  PortfolioKimiPage4: {
    category: "portfolio",
    navPageType: "home",
    tags: [
      "portfolio",
      "3d-artist",
      "motion-designer",
      "art-director",
      "cgi",
      "vfx",
      "animator",
      "creative",
      "dark",
      "cinematic",
      "showcase",
      "work",
      "home",
      "kimi",
    ],
    allowHero: true,
  },
  PricingKimiPage2: {
    category: "pricing",
    navPageType: "pricing",
    tags: [
      "pricing",
      "plans",
      "tiers",
      "subscription",
      "billing",
      "cloud",
      "storage",
      "saas",
      "toggle",
      "monthly-yearly",
      "comparison",
      "faq",
      "kimi",
      "no-hero",
    ],
    allowHero: false,
  },
  ProductDetailKimiPage3: {
    category: "ecommerce",
    navPageType: "detail",
    tags: ["commerce","product","detail","image","gallery","size","color","selectors"],
    allowHero: false,
  },
  RealEstateKimiPage3: {
    category: "marketing",
    navPageType: "home",
    tags: ["estate","agency","property","search","listings","agents"],
    allowHero: true,
  },
  RestaurantKimiPage3: {
    category: "restaurant",
    navPageType: "home",
    tags: [
      "restaurant",
      "ramen",
      "izakaya",
      "japanese",
      "food",
      "menu",
      "dining",
      "reservation",
      "dark",
      "image-led",
      "home",
      "landing",
      "kimi",
    ],
    allowHero: true,
  },
  ResumeCvKimiPage3: {
    category: "portfolio",
    navPageType: "home",
    tags: ["personal","resume","experience","timeline","skills"],
    allowHero: true,
  },
  SalonBarberKimiPage2: {
    category: "marketing",
    navPageType: "home",
    tags: ["hair","salon","barbershop","services","pricing","gallery","book"],
    allowHero: true,
  },
  SpaWellnessKimiPage3: {
    category: "marketing",
    navPageType: "home",
    tags: ["wellness","retreat","treatments","gallery","booking"],
    allowHero: true,
  },
  SubscriptionBoxKimiPage3: {
    category: "ecommerce",
    navPageType: "home",
    tags: ["subscription","coffee","works","plan","tiers"],
    allowHero: true,
  },
  TeamKimiPage2: {
    category: "about",
    navPageType: "team",
    tags: ["company","team","people","leadership","culture"],
    allowHero: true,
  },
  TelehealthKimiPage3: {
    category: "marketing",
    navPageType: "home",
    tags: ["telehealth","platform","works","provider","network"],
    allowHero: true,
  },
  TestimonialsKimiPage2: {
    category: "marketing",
    navPageType: "home",
    tags: ["testimonials","case","studies","reviews","quotes","logos","metrics"],
    allowHero: true,
  },
  TourExperiencesKimiPage2: {
    category: "marketing",
    navPageType: "home",
    tags: ["tours","experiences","booking","activity","reviews"],
    allowHero: true,
  },
  TravelAgencyKimiPage2: {
    category: "marketing",
    navPageType: "home",
    tags: ["travel","agency","destinations","search","packages","reviews"],
    allowHero: true,
  },
  TutoringKimiPage3: {
    category: "marketing",
    navPageType: "home",
    tags: ["tutoring","service","subjects","tutors","book","session"],
    allowHero: true,
  },
  UniversityKimiPage3: {
    category: "marketing",
    navPageType: "home",
    tags: ["university","college","programs","campus","life","apply"],
    allowHero: true,
  },
  VacationRentalKimiPage3: {
    category: "marketing",
    navPageType: "home",
    tags: ["vacation","rental","airbnb","style","listing","photos","amenities","booking"],
    allowHero: true,
  },
  VideoStreamingKimiPage3: {
    category: "marketing",
    navPageType: "home",
    tags: ["video","streaming","service","featured","content","rows","plan"],
    allowHero: true,
  },
  WebinarKimiPage2: {
    category: "event",
    navPageType: "home",
    tags: ["webinar","registration","agenda","speakers","signup"],
    allowHero: true,
  },
  WeddingKimiPage2: {
    category: "event",
    navPageType: "home",
    tags: ["wedding","story","schedule","rsvp","gallery"],
    allowHero: true,
  },
  WineryBreweryKimiPage2: {
    category: "restaurant",
    navPageType: "home",
    tags: ["winery","brewery","rustic","premium","tastings","story","visit"],
    allowHero: true,
  },
  WriterAuthorKimiPage3: {
    category: "portfolio",
    navPageType: "home",
    tags: ["author","book","about","reviews","links"],
    allowHero: true,
  },
  YogaStudioKimiPage3: {
    category: "marketing",
    navPageType: "home",
    tags: ["yoga","meditation","studio","serene","class","schedule","pricing"],
    allowHero: true,
  },

  AgencyKimiPage5: {
    category: "agency",
    navPageType: "home",
    tags: ["agency", "studio", "creative", "design", "portfolio", "work", "services", "home", "kimi"],
    allowHero: true,
  },
  AiProductKimiPage5: {
    category: "saas",
    navPageType: "home",
    tags: ["product","generative","writing","assistant"],
    allowHero: true,
  },
  AiProductKimiPage9: {
    category: "saas",
    navPageType: "home",
    tags: ["product","generative","writing","assistant"],
    allowHero: true,
  },
  AutoDealershipKimiPage3: {
    category: "marketing",
    navPageType: "home",
    tags: ["dealership","inventory","financing","test","drive"],
    allowHero: true,
  },
  BakeryKimiPage3: {
    category: "restaurant",
    navPageType: "home",
    tags: ["bakery","warm","product","showcase","order","visit"],
    allowHero: true,
  },
  BarNightclubKimiPage3: {
    category: "restaurant",
    navPageType: "home",
    tags: ["nightclub","dark","vibrant","events","drinks","menu","reservations"],
    allowHero: true,
  },
  CafeKimiPage3: {
    category: "restaurant",
    navPageType: "home",
    tags: ["cozy","coffee","cafe","menu","story","location"],
    allowHero: true,
  },
  ChurchKimiPage3: {
    category: "marketing",
    navPageType: "home",
    tags: ["church","religious","community","warm","service","times","events","give"],
    allowHero: true,
  },
  CleaningServiceKimiPage3: {
    category: "marketing",
    navPageType: "home",
    tags: ["home","cleaning","service","services","pricing","book"],
    allowHero: true,
  },
  ComingSoonKimiPage3: {
    category: "marketing",
    navPageType: "home",
    tags: ["coming","soon","waitlist","countdown","email","capture"],
    allowHero: true,
  },
  CommunityForumKimiPage3: {
    category: "marketing",
    navPageType: "home",
    tags: ["community","forum","platform","topics","join"],
    allowHero: true,
  },
  CrowdfundingKimiPage3: {
    category: "marketing",
    navPageType: "home",
    tags: ["crowdfunding","campaign","progress","story","rewards","tiers"],
    allowHero: true,
  },
  DocsKimiPage10: {
    category: "saas",
    navPageType: "index",
    tags: ["developer","documentation","sidebar","search","getting","started","code","block"],
    allowHero: false,
  },
  DocsKimiPage6: {
    category: "saas",
    navPageType: "index",
    tags: ["developer","documentation","sidebar","search","getting","started","code","block"],
    allowHero: false,
  },
  DocsKimiPage7: {
    category: "saas",
    navPageType: "index",
    tags: ["developer","documentation","sidebar","search","getting","started","code","block"],
    allowHero: false,
  },
  DocsKimiPage8: {
    category: "saas",
    navPageType: "index",
    tags: ["developer","documentation","sidebar","search","getting","started","code","block"],
    allowHero: false,
  },
  DocsKimiPage9: {
    category: "saas",
    navPageType: "index",
    tags: ["developer","documentation","sidebar","search","getting","started","code","block"],
    allowHero: false,
  },
  EcommerceKimiPage4: {
    category: "ecommerce",
    navPageType: "home",
    tags: ["ecommerce", "shop", "store", "sneakers", "products", "retail", "catalog", "kimi"],
    allowHero: true,
  },
  EcommerceKimiPage5: {
    category: "ecommerce",
    navPageType: "home",
    tags: ["ecommerce", "shop", "store", "sneakers", "products", "retail", "catalog", "kimi"],
    allowHero: true,
  },
  EducationKimiPage4: {
    category: "marketing",
    navPageType: "home",
    tags: ["education","academy","learning","platform","courses","outcomes","instructors","enrollment"],
    allowHero: true,
  },
  EducationKimiPage5: {
    category: "marketing",
    navPageType: "home",
    tags: ["education","academy","learning","platform","courses","outcomes","instructors","enrollment"],
    allowHero: true,
  },
  EventKimiPage3: {
    category: "event",
    navPageType: "home",
    tags: [
      "event",
      "conference",
      "summit",
      "tech",
      "speakers",
      "schedule",
      "sponsors",
      "register",
      "tickets",
      "countdown",
      "dark",
      "home",
      "landing",
      "kimi",
    ],
    allowHero: true,
  },
  FoodTruckKimiPage3: {
    category: "restaurant",
    navPageType: "home",
    tags: ["food","truck","menu","locations","schedule","catering"],
    allowHero: true,
  },
  HotelResortKimiPage3: {
    category: "marketing",
    navPageType: "home",
    tags: ["luxury","hotel","resort","rooms","amenities","gallery","booking"],
    allowHero: true,
  },
  JobBoardKimiPage3: {
    category: "marketing",
    navPageType: "list",
    tags: ["board","careers","search","listings","categories"],
    allowHero: true,
  },
  LandscapingKimiPage3: {
    category: "marketing",
    navPageType: "home",
    tags: ["landscaping","company","portfolio","services","quote"],
    allowHero: true,
  },
  LinkInBioKimiPage3: {
    category: "portfolio",
    navPageType: "home",
    tags: ["link","personal","avatar","buttons"],
    allowHero: true,
  },
  MembershipClubKimiPage3: {
    category: "marketing",
    navPageType: "home",
    tags: ["membership","club","benefits","tiers","join"],
    allowHero: true,
  },
  MusicFestivalKimiPage3: {
    category: "event",
    navPageType: "home",
    tags: ["music","festival","bold","lineup","dates","tickets"],
    allowHero: true,
  },
  PetVeterinaryKimiPage3: {
    category: "marketing",
    navPageType: "home",
    tags: ["veterinary","clinic","services","friendly","appointment"],
    allowHero: true,
  },
  PortfolioKimiPage5: {
    category: "portfolio",
    navPageType: "home",
    tags: [
      "portfolio",
      "3d-artist",
      "motion-designer",
      "art-director",
      "cgi",
      "vfx",
      "animator",
      "creative",
      "dark",
      "cinematic",
      "showcase",
      "work",
      "home",
      "kimi",
    ],
    allowHero: true,
  },
  PropertyListingKimiPage3: {
    category: "marketing",
    navPageType: "home",
    tags: ["single","property","luxury","listing","gallery","features","tour","booking"],
    allowHero: true,
  },
  SalonBarberKimiPage3: {
    category: "marketing",
    navPageType: "home",
    tags: ["hair","salon","barbershop","services","pricing","gallery","book"],
    allowHero: true,
  },
  TourExperiencesKimiPage3: {
    category: "marketing",
    navPageType: "home",
    tags: ["tours","experiences","booking","activity","reviews"],
    allowHero: true,
  },
  WebinarKimiPage3: {
    category: "event",
    navPageType: "home",
    tags: ["webinar","registration","agenda","speakers","signup"],
    allowHero: true,
  },
  WeddingKimiPage3: {
    category: "event",
    navPageType: "home",
    tags: ["wedding","story","schedule","rsvp","gallery"],
    allowHero: true,
  },
  WineryBreweryKimiPage3: {
    category: "restaurant",
    navPageType: "home",
    tags: ["winery","brewery","rustic","premium","tastings","story","visit"],
    allowHero: true,
  },

  AuthKimiPage: {
    category: "marketing",
    navPageType: "home",
    tags: ["sign","authentication","email","password","form","social","login","options"],
    allowHero: true,
  },
  FeaturesKimiPage: {
    category: "marketing",
    navPageType: "home",
    tags: ["features","showcase","highlighting","product","capabilities","icon","grids","detailed"],
    allowHero: true,
  },
  MenuKimiPage: {
    category: "restaurant",
    navPageType: "home",
    tags: ["restaurant","menu","categorized","food","items","descriptions","prices","dietary"],
    allowHero: true,
  },
  ScheduleKimiPage: {
    category: "event",
    navPageType: "home",
    tags: ["class","schedule","calendar","time","slots","session","instructor","info"],
    allowHero: true,
  },
  AuthKimiPage2: {
    category: "marketing",
    navPageType: "home",
    tags: ["sign","authentication","email","password","form","social","login","options"],
    allowHero: true,
  },
  AuthKimiPage3: {
    category: "marketing",
    navPageType: "home",
    tags: ["sign","authentication","email","password","form","social","login","options"],
    allowHero: true,
  },
  AuthKimiPage4: {
    category: "marketing",
    navPageType: "home",
    tags: ["sign","authentication","email","password","form","social","login","options"],
    allowHero: true,
  },
  AuthKimiPage5: {
    category: "marketing",
    navPageType: "home",
    tags: ["sign","authentication","email","password","form","social","login","options"],
    allowHero: true,
  },
  FeaturesKimiPage2: {
    category: "marketing",
    navPageType: "home",
    tags: ["features","showcase","highlighting","product","capabilities","icon","grids","detailed"],
    allowHero: true,
  },
  FeaturesKimiPage3: {
    category: "marketing",
    navPageType: "home",
    tags: ["features","showcase","highlighting","product","capabilities","icon","grids","detailed"],
    allowHero: true,
  },
  FeaturesKimiPage4: {
    category: "marketing",
    navPageType: "home",
    tags: ["features","showcase","highlighting","product","capabilities","icon","grids","detailed"],
    allowHero: true,
  },
  FeaturesKimiPage5: {
    category: "marketing",
    navPageType: "home",
    tags: ["features","showcase","highlighting","product","capabilities","icon","grids","detailed"],
    allowHero: true,
  },
  MenuKimiPage2: {
    category: "restaurant",
    navPageType: "home",
    tags: ["restaurant","menu","categorized","food","items","descriptions","prices","dietary"],
    allowHero: true,
  },
  MenuKimiPage3: {
    category: "restaurant",
    navPageType: "home",
    tags: ["restaurant","menu","categorized","food","items","descriptions","prices","dietary"],
    allowHero: true,
  },
  MenuKimiPage4: {
    category: "restaurant",
    navPageType: "home",
    tags: ["restaurant","menu","categorized","food","items","descriptions","prices","dietary"],
    allowHero: true,
  },
  MenuKimiPage5: {
    category: "restaurant",
    navPageType: "home",
    tags: ["restaurant","menu","categorized","food","items","descriptions","prices","dietary"],
    allowHero: true,
  },
  ScheduleKimiPage2: {
    category: "event",
    navPageType: "home",
    tags: ["class","schedule","calendar","time","slots","session","instructor","info"],
    allowHero: true,
  },
  ScheduleKimiPage3: {
    category: "event",
    navPageType: "home",
    tags: ["class","schedule","calendar","time","slots","session","instructor","info"],
    allowHero: true,
  },
  ScheduleKimiPage4: {
    category: "event",
    navPageType: "home",
    tags: ["class","schedule","calendar","time","slots","session","instructor","info"],
    allowHero: true,
  },
  ScheduleKimiPage5: {
    category: "event",
    navPageType: "home",
    tags: ["class","schedule","calendar","time","slots","session","instructor","info"],
    allowHero: true,
  },

}

// Nav templates per category: first label is the home/landing route.
export const NAV_TEMPLATES: Record<Category, { label: string; type: NavPageType }[]> = {
  marketing: [
    { label: "Home", type: "home" },
    { label: "Features", type: "features" },
    { label: "Pricing", type: "pricing" },
    { label: "About", type: "about" },
    { label: "Contact", type: "contact" },
  ],
  saas: [
    { label: "Home", type: "home" },
    { label: "Features", type: "features" },
    { label: "Pricing", type: "pricing" },
    { label: "Contact", type: "contact" },
  ],
  ecommerce: [
    { label: "Home", type: "home" },
    { label: "Shop", type: "list" },
    { label: "About", type: "about" },
    { label: "Contact", type: "contact" },
  ],
  blog: [
    { label: "Home", type: "index" },
    { label: "About", type: "about" },
    { label: "Contact", type: "contact" },
  ],
  portfolio: [
    { label: "Home", type: "home" },
    { label: "Work", type: "gallery" },
    { label: "About", type: "about" },
    { label: "Contact", type: "contact" },
  ],
  pricing: [
    { label: "Home", type: "home" },
    { label: "Pricing", type: "pricing" },
    { label: "About", type: "about" },
    { label: "Contact", type: "contact" },
  ],
  about: [
    { label: "Home", type: "home" },
    { label: "About", type: "about" },
    { label: "Team", type: "team" },
    { label: "Contact", type: "contact" },
  ],
  contact: [
    { label: "Home", type: "home" },
    { label: "About", type: "about" },
    { label: "Contact", type: "contact" },
  ],
  agency: [
    { label: "Home", type: "home" },
    { label: "Work", type: "gallery" },
    { label: "Services", type: "features" },
    { label: "About", type: "about" },
    { label: "Contact", type: "contact" },
  ],
  restaurant: [
    { label: "Home", type: "home" },
    { label: "Menu", type: "menu" },
    { label: "About", type: "about" },
    { label: "Contact", type: "contact" },
  ],
  event: [
    { label: "Home", type: "home" },
    { label: "Schedule", type: "schedule" },
    { label: "Pricing", type: "pricing" },
    { label: "Contact", type: "contact" },
  ],
  dashboard: [
    { label: "Overview", type: "dashboard" },
    { label: "Reports", type: "list" },
    { label: "Settings", type: "about" },
  ],
  auth: [
    { label: "Sign In", type: "auth" },
  ],
  game: [
    { label: "Home", type: "home" },
    { label: "Features", type: "features" },
    { label: "Leaderboard", type: "gallery" },
    { label: "Contact", type: "contact" },
  ],
}

// Filter BLOCK_TAXONOMY entries by `where`, pick one deterministically using rng(),
// else return `fallback`. rng() is expected to return a float in [0, 1).
export function pickBlock(
  rng: () => number,
  where: (m: BlockMeta) => boolean,
  fallback: string,
): string {
  const matches = Object.entries(BLOCK_TAXONOMY).filter(([, meta]) => where(meta))
  if (matches.length === 0) return fallback
  const idx = Math.min(matches.length - 1, Math.floor(rng() * matches.length))
  return matches[idx][0]
}

// NOTE: keyword-heuristic prompt classification was removed by design. Block/page
// selection is done by a real AI call (Groq gpt-oss-120b) that reads each block's
// name + description and returns a relevance shortlist; the orchestrator then
// random-picks from it. See src/genui/orchestrator.ts (planSystem/planUser/parsePlan).
// The `category` field on each BlockMeta below is retained only as block metadata
// (e.g. to detect auth blocks for the single-page sign-in path) — it is NOT used to
// classify prompts.
